-- ===========================================================================
-- Nexgile WealthAgent — Supabase / PostgreSQL schema
--
-- Generated from the SQLAlchemy models in backend/app/models so this file and
-- the ORM cannot drift apart. Regenerate with:
--
--     python -m app.seeds.emit_schema        (from backend/)
--
-- Apply it in the Supabase SQL editor, or:
--     psql "$DATABASE_URL" -f supabase/schema.sql
--
-- Then load the demonstration dataset:
--     DATABASE_URL="postgresql://..." python seed.py
--
-- Conventions
--   * Primary keys are UUID strings generated by the application.
--   * Every table carries created_at / updated_at.
--   * Foreign keys use ON DELETE CASCADE for owned records and SET NULL for
--     references that should survive the parent being removed.
--   * Indexes back every foreign key and every column the API filters on.
-- ===========================================================================

BEGIN;

CREATE TABLE benchmarks (
	code VARCHAR(32) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	description TEXT, 
	composition JSON NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);

CREATE TABLE charities (
	name VARCHAR(160) NOT NULL, 
	ein_masked VARCHAR(24), 
	mission_area VARCHAR(80) NOT NULL, 
	location VARCHAR(120), 
	rating FLOAT, 
	is_qualified BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE custodians (
	name VARCHAR(120) NOT NULL, 
	short_name VARCHAR(48) NOT NULL, 
	connection_type VARCHAR(32) NOT NULL, 
	feed_status VARCHAR(24) NOT NULL, 
	logo_hint VARCHAR(32), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE education_content (
	title VARCHAR(200) NOT NULL, 
	content_type VARCHAR(32) NOT NULL, 
	learning_path VARCHAR(96) NOT NULL, 
	level VARCHAR(24) NOT NULL, 
	duration_minutes INTEGER NOT NULL, 
	summary TEXT NOT NULL, 
	body TEXT, 
	tags JSON NOT NULL, 
	published_on DATE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE permissions (
	key VARCHAR(64) NOT NULL, 
	description TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_permissions_key ON permissions (key);

CREATE TABLE roles (
	key VARCHAR(48) NOT NULL, 
	label VARCHAR(96) NOT NULL, 
	description TEXT, 
	home_route VARCHAR(96) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_roles_key ON roles (key);

CREATE TABLE securities (
	symbol VARCHAR(24) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	security_type VARCHAR(32) NOT NULL, 
	asset_class VARCHAR(32) NOT NULL, 
	sector VARCHAR(64), 
	region VARCHAR(48) NOT NULL, 
	currency VARCHAR(8) NOT NULL, 
	last_price FLOAT NOT NULL, 
	previous_close FLOAT NOT NULL, 
	dividend_yield FLOAT NOT NULL, 
	expense_ratio FLOAT, 
	beta FLOAT NOT NULL, 
	annualised_volatility FLOAT NOT NULL, 
	esg_score FLOAT, 
	is_municipal BOOLEAN NOT NULL, 
	substantially_identical_to VARCHAR(24), 
	price_as_of TIMESTAMP WITH TIME ZONE, 
	price_status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_securities_asset_class ON securities (asset_class);

CREATE INDEX ix_securities_class ON securities (asset_class, sector);

CREATE UNIQUE INDEX ix_securities_symbol ON securities (symbol);

CREATE TABLE users (
	email VARCHAR(255) NOT NULL, 
	full_name VARCHAR(160) NOT NULL, 
	role VARCHAR(48) NOT NULL, 
	title VARCHAR(120), 
	phone VARCHAR(40), 
	avatar_initials VARCHAR(4), 
	password_hash VARCHAR(255), 
	supabase_user_id VARCHAR(64), 
	is_active BOOLEAN NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	demo_label VARCHAR(64), 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	timezone VARCHAR(64) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE INDEX ix_users_role ON users (role);

CREATE INDEX ix_users_role_active ON users (role, is_active);

CREATE INDEX ix_users_supabase_user_id ON users (supabase_user_id);

CREATE TABLE advisor_teams (
	name VARCHAR(120) NOT NULL, 
	region VARCHAR(80), 
	lead_advisor_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(lead_advisor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE households (
	name VARCHAR(160) NOT NULL, 
	segment VARCHAR(48) NOT NULL, 
	primary_advisor_id VARCHAR(36), 
	risk_profile VARCHAR(32) NOT NULL, 
	since DATE, 
	city VARCHAR(80), 
	state VARCHAR(40), 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(primary_advisor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_households_name ON households (name);

CREATE INDEX ix_households_primary_advisor_id ON households (primary_advisor_id);

CREATE TABLE role_permissions (
	role_id VARCHAR(36) NOT NULL, 
	permission_id VARCHAR(36) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX ix_role_permissions_permission_id ON role_permissions (permission_id);

CREATE INDEX ix_role_permissions_role_id ON role_permissions (role_id);

CREATE TABLE saved_views (
	user_id VARCHAR(36) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	query VARCHAR(255) NOT NULL, 
	categories JSON NOT NULL, 
	is_pinned BOOLEAN NOT NULL, 
	use_count INTEGER NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_saved_views_user_id ON saved_views (user_id);

CREATE TABLE search_history (
	user_id VARCHAR(36) NOT NULL, 
	query VARCHAR(255) NOT NULL, 
	result_count INTEGER NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_search_history_user_id ON search_history (user_id);

CREATE INDEX ix_search_user_time ON search_history (user_id, created_at);

CREATE TABLE sponsors (
	name VARCHAR(160) NOT NULL, 
	industry VARCHAR(80) NOT NULL, 
	employee_count INTEGER NOT NULL, 
	ein_masked VARCHAR(24), 
	location VARCHAR(120), 
	relationship_since DATE, 
	primary_contact_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(primary_contact_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE advisor_assignments (
	advisor_id VARCHAR(36) NOT NULL, 
	household_id VARCHAR(36) NOT NULL, 
	team_id VARCHAR(36), 
	role_on_account VARCHAR(48) NOT NULL, 
	is_primary BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_advisor_household_role UNIQUE (advisor_id, household_id, role_on_account), 
	FOREIGN KEY(advisor_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(team_id) REFERENCES advisor_teams (id) ON DELETE SET NULL
);

CREATE INDEX ix_advisor_assignments_advisor_id ON advisor_assignments (advisor_id);

CREATE INDEX ix_assignment_household ON advisor_assignments (household_id);

CREATE TABLE audit_events (
	actor_id VARCHAR(36), 
	actor_name VARCHAR(160) NOT NULL, 
	actor_role VARCHAR(48), 
	household_id VARCHAR(36), 
	action VARCHAR(64) NOT NULL, 
	entity_type VARCHAR(48) NOT NULL, 
	entity_id VARCHAR(36), 
	entity_label VARCHAR(200), 
	status VARCHAR(24) NOT NULL, 
	summary TEXT, 
	before_state JSON, 
	after_state JSON, 
	ip_address VARCHAR(64), 
	user_agent VARCHAR(255), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(actor_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE SET NULL
);

CREATE INDEX ix_audit_actor_time ON audit_events (actor_id, created_at);

CREATE INDEX ix_audit_entity ON audit_events (entity_type, entity_id);

CREATE INDEX ix_audit_events_action ON audit_events (action);

CREATE INDEX ix_audit_events_actor_id ON audit_events (actor_id);

CREATE INDEX ix_audit_events_entity_type ON audit_events (entity_type);

CREATE INDEX ix_audit_events_household_id ON audit_events (household_id);

CREATE INDEX ix_audit_household_time ON audit_events (household_id, created_at);

CREATE TABLE clients (
	user_id VARCHAR(36), 
	household_id VARCHAR(36) NOT NULL, 
	full_name VARCHAR(160) NOT NULL, 
	birth_date DATE, 
	retirement_age INTEGER NOT NULL, 
	filing_status VARCHAR(32) NOT NULL, 
	marginal_tax_rate FLOAT NOT NULL, 
	ltcg_tax_rate FLOAT NOT NULL, 
	state_tax_rate FLOAT NOT NULL, 
	annual_income FLOAT NOT NULL, 
	annual_savings FLOAT NOT NULL, 
	risk_tolerance VARCHAR(32) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	segment VARCHAR(48) NOT NULL, 
	onboarded_on DATE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_clients_full_name ON clients (full_name);

CREATE INDEX ix_clients_household_id ON clients (household_id);

CREATE UNIQUE INDEX ix_clients_user_id ON clients (user_id);

CREATE TABLE estate_plans (
	household_id VARCHAR(36) NOT NULL, 
	plan_name VARCHAR(160) NOT NULL, 
	document_type VARCHAR(48) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	executed_on DATE, 
	last_reviewed_on DATE, 
	next_review_due DATE, 
	attorney VARCHAR(120), 
	jurisdiction VARCHAR(80), 
	executor VARCHAR(120), 
	notes TEXT, 
	estimated_estate_value FLOAT NOT NULL, 
	projected_estate_tax FLOAT NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_estate_plans_household_id ON estate_plans (household_id);

CREATE TABLE gifts (
	household_id VARCHAR(36) NOT NULL, 
	charity_id VARCHAR(36), 
	security_id VARCHAR(36), 
	recipient VARCHAR(160) NOT NULL, 
	gift_type VARCHAR(48) NOT NULL, 
	amount FLOAT NOT NULL, 
	cost_basis FLOAT, 
	gifted_on DATE NOT NULL, 
	tax_year INTEGER NOT NULL, 
	uses_annual_exclusion BOOLEAN NOT NULL, 
	is_qcd BOOLEAN NOT NULL, 
	deduction_amount FLOAT NOT NULL, 
	capital_gain_avoided FLOAT NOT NULL, 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(charity_id) REFERENCES charities (id) ON DELETE SET NULL, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE SET NULL
);

CREATE INDEX ix_gifts_household_id ON gifts (household_id);

CREATE INDEX ix_gifts_tax_year ON gifts (tax_year);

CREATE TABLE giving_plans (
	household_id VARCHAR(36) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	tax_year INTEGER NOT NULL, 
	target_amount FLOAT NOT NULL, 
	committed_amount FLOAT NOT NULL, 
	mission_focus VARCHAR(120) NOT NULL, 
	strategy VARCHAR(120) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	review_date DATE, 
	last_updated_at TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_giving_plans_household_id ON giving_plans (household_id);

CREATE TABLE household_members (
	household_id VARCHAR(36) NOT NULL, 
	full_name VARCHAR(160) NOT NULL, 
	relationship_type VARCHAR(48) NOT NULL, 
	birth_date DATE, 
	is_dependent BOOLEAN NOT NULL, 
	email VARCHAR(255), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_household_members_household_id ON household_members (household_id);

CREATE TABLE meetings (
	household_id VARCHAR(36) NOT NULL, 
	advisor_id VARCHAR(36), 
	title VARCHAR(200) NOT NULL, 
	meeting_type VARCHAR(48) NOT NULL, 
	starts_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	duration_minutes INTEGER NOT NULL, 
	location VARCHAR(120) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	agenda JSON NOT NULL, 
	notes TEXT, 
	summary TEXT, 
	attendees JSON NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(advisor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_meetings_advisor_id ON meetings (advisor_id);

CREATE INDEX ix_meetings_household_id ON meetings (household_id);

CREATE INDEX ix_meetings_household_start ON meetings (household_id, starts_at);

CREATE INDEX ix_meetings_starts_at ON meetings (starts_at);

CREATE TABLE message_threads (
	household_id VARCHAR(36) NOT NULL, 
	subject VARCHAR(200) NOT NULL, 
	topic VARCHAR(48) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	last_message_at TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_message_threads_household_id ON message_threads (household_id);

CREATE INDEX ix_message_threads_last_message_at ON message_threads (last_message_at);

CREATE TABLE plans (
	sponsor_id VARCHAR(36) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	plan_number VARCHAR(16) NOT NULL, 
	plan_type VARCHAR(32) NOT NULL, 
	plan_year_end DATE NOT NULL, 
	total_assets FLOAT NOT NULL, 
	eligible_employees INTEGER NOT NULL, 
	participating_employees INTEGER NOT NULL, 
	average_deferral_rate FLOAT NOT NULL, 
	employer_match_formula VARCHAR(160) NOT NULL, 
	vesting_schedule VARCHAR(96) NOT NULL, 
	auto_enrollment BOOLEAN NOT NULL, 
	auto_enrollment_rate FLOAT NOT NULL, 
	auto_escalation BOOLEAN NOT NULL, 
	auto_escalation_cap FLOAT NOT NULL, 
	loans_allowed BOOLEAN NOT NULL, 
	hardship_allowed BOOLEAN NOT NULL, 
	recordkeeper VARCHAR(120) NOT NULL, 
	advisor_id VARCHAR(36), 
	plan_health_score FLOAT NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(sponsor_id) REFERENCES sponsors (id) ON DELETE CASCADE, 
	FOREIGN KEY(advisor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_plans_sponsor_id ON plans (sponsor_id);

CREATE TABLE portfolios (
	household_id VARCHAR(36) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	strategy VARCHAR(64) NOT NULL, 
	benchmark_id VARCHAR(36), 
	inception_date DATE, 
	management_fee_bps INTEGER NOT NULL, 
	as_of TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(benchmark_id) REFERENCES benchmarks (id) ON DELETE SET NULL
);

CREATE INDEX ix_portfolios_household_id ON portfolios (household_id);

CREATE TABLE powers_of_attorney (
	household_id VARCHAR(36) NOT NULL, 
	poa_type VARCHAR(48) NOT NULL, 
	principal VARCHAR(120) NOT NULL, 
	agent VARCHAR(120) NOT NULL, 
	successor_agent VARCHAR(120), 
	executed_on DATE, 
	status VARCHAR(24) NOT NULL, 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_powers_of_attorney_household_id ON powers_of_attorney (household_id);

CREATE TABLE tasks (
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	assignee_id VARCHAR(36), 
	household_id VARCHAR(36), 
	category VARCHAR(48) NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	due_date DATE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	sla_days INTEGER, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(assignee_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE
);

CREATE INDEX ix_tasks_assignee_id ON tasks (assignee_id);

CREATE INDEX ix_tasks_assignee_status ON tasks (assignee_id, status);

CREATE INDEX ix_tasks_household_id ON tasks (household_id);

CREATE TABLE accounts (
	household_id VARCHAR(36) NOT NULL, 
	client_id VARCHAR(36), 
	custodian_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	account_number_masked VARCHAR(32) NOT NULL, 
	account_type VARCHAR(32) NOT NULL, 
	account_subtype VARCHAR(48), 
	tax_treatment VARCHAR(32) NOT NULL, 
	registration VARCHAR(64) NOT NULL, 
	currency VARCHAR(8) NOT NULL, 
	balance FLOAT NOT NULL, 
	cash_balance FLOAT NOT NULL, 
	is_liability BOOLEAN NOT NULL, 
	interest_rate FLOAT, 
	minimum_payment FLOAT, 
	status VARCHAR(24) NOT NULL, 
	is_external BOOLEAN NOT NULL, 
	opened_on DATE, 
	last_synced_at TIMESTAMP WITH TIME ZONE, 
	data_source VARCHAR(48) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(client_id) REFERENCES clients (id) ON DELETE SET NULL, 
	FOREIGN KEY(custodian_id) REFERENCES custodians (id) ON DELETE SET NULL
);

CREATE INDEX ix_accounts_account_type ON accounts (account_type);

CREATE INDEX ix_accounts_client ON accounts (client_id);

CREATE INDEX ix_accounts_household_id ON accounts (household_id);

CREATE INDEX ix_accounts_household_type ON accounts (household_id, account_type);

CREATE TABLE action_items (
	meeting_id VARCHAR(36), 
	household_id VARCHAR(36), 
	thread_id VARCHAR(36), 
	title VARCHAR(200) NOT NULL, 
	owner VARCHAR(120) NOT NULL, 
	due_date DATE, 
	status VARCHAR(24) NOT NULL, 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(thread_id) REFERENCES message_threads (id) ON DELETE SET NULL
);

CREATE INDEX ix_action_items_household_id ON action_items (household_id);

CREATE INDEX ix_action_items_meeting_id ON action_items (meeting_id);

CREATE TABLE alerts (
	user_id VARCHAR(36), 
	household_id VARCHAR(36), 
	plan_id VARCHAR(36), 
	category VARCHAR(48) NOT NULL, 
	severity VARCHAR(16) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	entity_type VARCHAR(48), 
	entity_id VARCHAR(36), 
	action_url VARCHAR(200), 
	due_date DATE, 
	read_at TIMESTAMP WITH TIME ZONE, 
	dismissed_at TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE
);

CREATE INDEX ix_alerts_category ON alerts (category);

CREATE INDEX ix_alerts_household_category ON alerts (household_id, category);

CREATE INDEX ix_alerts_user_id ON alerts (user_id);

CREATE INDEX ix_alerts_user_read ON alerts (user_id, read_at);

CREATE TABLE allocations (
	portfolio_id VARCHAR(36) NOT NULL, 
	asset_class VARCHAR(32) NOT NULL, 
	kind VARCHAR(24) NOT NULL, 
	target_weight FLOAT NOT NULL, 
	min_weight FLOAT NOT NULL, 
	max_weight FLOAT NOT NULL, 
	tolerance_band FLOAT NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_allocation_target UNIQUE (portfolio_id, asset_class, kind), 
	FOREIGN KEY(portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE INDEX ix_allocations_portfolio_id ON allocations (portfolio_id);

CREATE TABLE approvals (
	household_id VARCHAR(36), 
	plan_id VARCHAR(36), 
	entity_type VARCHAR(48) NOT NULL, 
	entity_id VARCHAR(36), 
	title VARCHAR(200) NOT NULL, 
	summary TEXT, 
	status VARCHAR(24) NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	requested_by_id VARCHAR(36), 
	assigned_to_id VARCHAR(36), 
	decided_by_id VARCHAR(36), 
	required_role VARCHAR(48) NOT NULL, 
	submitted_at TIMESTAMP WITH TIME ZONE, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	due_date DATE, 
	decision_note TEXT, 
	payload JSON NOT NULL, 
	estimated_impact FLOAT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(requested_by_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(assigned_to_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(decided_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_approvals_assigned_to_id ON approvals (assigned_to_id);

CREATE INDEX ix_approvals_entity_id ON approvals (entity_id);

CREATE INDEX ix_approvals_entity_type ON approvals (entity_type);

CREATE INDEX ix_approvals_household ON approvals (household_id);

CREATE INDEX ix_approvals_household_id ON approvals (household_id);

CREATE INDEX ix_approvals_requested_by_id ON approvals (requested_by_id);

CREATE INDEX ix_approvals_status ON approvals (status);

CREATE INDEX ix_approvals_status_type ON approvals (status, entity_type);

CREATE TABLE fees (
	plan_id VARCHAR(36) NOT NULL, 
	vendor VARCHAR(120) NOT NULL, 
	fee_type VARCHAR(48) NOT NULL, 
	payer VARCHAR(32) NOT NULL, 
	annual_amount FLOAT NOT NULL, 
	per_participant_amount FLOAT NOT NULL, 
	basis_points FLOAT NOT NULL, 
	benchmark_basis_points FLOAT NOT NULL, 
	revenue_sharing FLOAT NOT NULL, 
	contract_end DATE, 
	sla_score FLOAT, 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE
);

CREATE INDEX ix_fees_plan_id ON fees (plan_id);

CREATE TABLE filings (
	plan_id VARCHAR(36) NOT NULL, 
	filing_type VARCHAR(48) NOT NULL, 
	tax_year INTEGER NOT NULL, 
	due_date DATE NOT NULL, 
	extended_due_date DATE, 
	filed_on DATE, 
	status VARCHAR(24) NOT NULL, 
	preparer VARCHAR(120), 
	auditor VARCHAR(120), 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE
);

CREATE INDEX ix_filings_plan_id ON filings (plan_id);

CREATE TABLE goals (
	household_id VARCHAR(36) NOT NULL, 
	client_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	goal_type VARCHAR(32) NOT NULL, 
	description TEXT, 
	target_amount FLOAT NOT NULL, 
	current_amount FLOAT NOT NULL, 
	target_date DATE NOT NULL, 
	monthly_contribution FLOAT NOT NULL, 
	expected_return FLOAT NOT NULL, 
	inflation_rate FLOAT NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	owner_label VARCHAR(96), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(client_id) REFERENCES clients (id) ON DELETE SET NULL
);

CREATE INDEX ix_goals_goal_type ON goals (goal_type);

CREATE INDEX ix_goals_household_id ON goals (household_id);

CREATE INDEX ix_goals_household_type ON goals (household_id, goal_type);

CREATE TABLE investment_options (
	plan_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	ticker VARCHAR(16), 
	asset_category VARCHAR(64) NOT NULL, 
	expense_ratio FLOAT NOT NULL, 
	category_median_expense FLOAT NOT NULL, 
	plan_assets FLOAT NOT NULL, 
	participants_invested INTEGER NOT NULL, 
	three_year_return FLOAT NOT NULL, 
	five_year_return FLOAT NOT NULL, 
	benchmark_three_year FLOAT NOT NULL, 
	peer_rank_percentile INTEGER NOT NULL, 
	ips_status VARCHAR(24) NOT NULL, 
	watch_reason TEXT, 
	is_qdia BOOLEAN NOT NULL, 
	revenue_share_bps INTEGER NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE SET NULL
);

CREATE INDEX ix_investment_options_plan_id ON investment_options (plan_id);

CREATE TABLE participants (
	plan_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36), 
	full_name VARCHAR(160) NOT NULL, 
	employee_id_masked VARCHAR(24) NOT NULL, 
	birth_date DATE NOT NULL, 
	hire_date DATE NOT NULL, 
	annual_salary FLOAT NOT NULL, 
	deferral_rate FLOAT NOT NULL, 
	roth_deferral_rate FLOAT NOT NULL, 
	account_balance FLOAT NOT NULL, 
	roth_balance FLOAT NOT NULL, 
	employer_balance FLOAT NOT NULL, 
	vested_percentage FLOAT NOT NULL, 
	is_hce BOOLEAN NOT NULL, 
	is_auto_enrolled BOOLEAN NOT NULL, 
	has_beneficiary BOOLEAN NOT NULL, 
	retirement_age INTEGER NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	engagement_score FLOAT NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_participants_full_name ON participants (full_name);

CREATE INDEX ix_participants_plan_id ON participants (plan_id);

CREATE INDEX ix_participants_plan_status ON participants (plan_id, status);

CREATE INDEX ix_participants_user_id ON participants (user_id);

CREATE TABLE performance (
	portfolio_id VARCHAR(36) NOT NULL, 
	as_of DATE NOT NULL, 
	market_value FLOAT NOT NULL, 
	net_flow FLOAT NOT NULL, 
	daily_return FLOAT NOT NULL, 
	benchmark_return FLOAT NOT NULL, 
	cumulative_index FLOAT NOT NULL, 
	benchmark_index FLOAT NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_performance_point UNIQUE (portfolio_id, as_of), 
	FOREIGN KEY(portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE INDEX ix_performance_asof ON performance (as_of);

CREATE INDEX ix_performance_portfolio_id ON performance (portfolio_id);

CREATE TABLE portfolio_positions (
	portfolio_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36) NOT NULL, 
	quantity FLOAT NOT NULL, 
	market_value FLOAT NOT NULL, 
	cost_basis FLOAT NOT NULL, 
	weight FLOAT NOT NULL, 
	as_of DATE NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE CASCADE
);

CREATE INDEX ix_portfolio_positions_portfolio_id ON portfolio_positions (portfolio_id);

CREATE INDEX ix_position_portfolio_asof ON portfolio_positions (portfolio_id, as_of);

CREATE TABLE reports (
	household_id VARCHAR(36), 
	plan_id VARCHAR(36), 
	report_type VARCHAR(48) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	benchmark_code VARCHAR(32), 
	status VARCHAR(24) NOT NULL, 
	generated_by_id VARCHAR(36), 
	generated_at TIMESTAMP WITH TIME ZONE, 
	sections JSON NOT NULL, 
	payload JSON NOT NULL, 
	assumptions JSON NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(generated_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_reports_household_id ON reports (household_id);

CREATE INDEX ix_reports_household_type ON reports (household_id, report_type);

CREATE INDEX ix_reports_report_type ON reports (report_type);

CREATE TABLE approval_events (
	approval_id VARCHAR(36) NOT NULL, 
	from_status VARCHAR(24), 
	to_status VARCHAR(24) NOT NULL, 
	actor_id VARCHAR(36), 
	actor_name VARCHAR(160) NOT NULL, 
	note TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE CASCADE, 
	FOREIGN KEY(actor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_approval_events_approval_id ON approval_events (approval_id);

CREATE TABLE contributions (
	participant_id VARCHAR(36) NOT NULL, 
	plan_id VARCHAR(36) NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	employee_pretax FLOAT NOT NULL, 
	employee_roth FLOAT NOT NULL, 
	employee_catchup FLOAT NOT NULL, 
	employer_match FLOAT NOT NULL, 
	employer_profit_sharing FLOAT NOT NULL, 
	tax_year INTEGER NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(participant_id) REFERENCES participants (id) ON DELETE CASCADE, 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE
);

CREATE INDEX ix_contrib_participant_period ON contributions (participant_id, period_end);

CREATE INDEX ix_contributions_participant_id ON contributions (participant_id);

CREATE INDEX ix_contributions_tax_year ON contributions (tax_year);

CREATE TABLE dafs (
	household_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	vehicle_type VARCHAR(48) NOT NULL, 
	sponsor_organisation VARCHAR(160), 
	balance FLOAT NOT NULL, 
	contributed_ytd FLOAT NOT NULL, 
	granted_ytd FLOAT NOT NULL, 
	annual_grant_target FLOAT NOT NULL, 
	payout_requirement FLOAT, 
	established_on DATE, 
	status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE SET NULL
);

CREATE INDEX ix_dafs_household_id ON dafs (household_id);

CREATE TABLE documents (
	household_id VARCHAR(36) NOT NULL, 
	uploaded_by_id VARCHAR(36), 
	account_id VARCHAR(36), 
	name VARCHAR(255) NOT NULL, 
	original_filename VARCHAR(255) NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	document_type VARCHAR(64), 
	tax_year INTEGER, 
	tags JSON NOT NULL, 
	description TEXT, 
	storage_key VARCHAR(512), 
	storage_backend VARCHAR(24) NOT NULL, 
	mime_type VARCHAR(120) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	current_version INTEGER NOT NULL, 
	review_status VARCHAR(24) NOT NULL, 
	suggested_category VARCHAR(32), 
	suggested_document_type VARCHAR(64), 
	classification_confidence FLOAT, 
	classification_source VARCHAR(48) NOT NULL, 
	classification_reasons JSON NOT NULL, 
	classification_accepted BOOLEAN, 
	expires_on DATE, 
	retention_until DATE, 
	is_confidential BOOLEAN NOT NULL, 
	uploaded_at TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE SET NULL
);

CREATE INDEX ix_documents_category ON documents (category);

CREATE INDEX ix_documents_household_category ON documents (household_id, category);

CREATE INDEX ix_documents_household_id ON documents (household_id);

CREATE INDEX ix_documents_name ON documents (name);

CREATE INDEX ix_documents_status ON documents (review_status);

CREATE TABLE education_progress (
	participant_id VARCHAR(36) NOT NULL, 
	content_id VARCHAR(36) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	progress_percent FLOAT NOT NULL, 
	score FLOAT, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(participant_id) REFERENCES participants (id) ON DELETE CASCADE, 
	FOREIGN KEY(content_id) REFERENCES education_content (id) ON DELETE CASCADE
);

CREATE INDEX ix_education_progress_participant_id ON education_progress (participant_id);

CREATE TABLE goal_accounts (
	goal_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36) NOT NULL, 
	allocation_percent FLOAT NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_goal_account UNIQUE (goal_id, account_id), 
	FOREIGN KEY(goal_id) REFERENCES goals (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_goal_accounts_account_id ON goal_accounts (account_id);

CREATE INDEX ix_goal_accounts_goal_id ON goal_accounts (goal_id);

CREATE TABLE holdings (
	account_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36) NOT NULL, 
	portfolio_id VARCHAR(36), 
	quantity FLOAT NOT NULL, 
	average_cost FLOAT NOT NULL, 
	acquired_on DATE, 
	as_of TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_holding_account_security UNIQUE (account_id, security_id), 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE CASCADE, 
	FOREIGN KEY(portfolio_id) REFERENCES portfolios (id) ON DELETE SET NULL
);

CREATE INDEX ix_holdings_account_id ON holdings (account_id);

CREATE INDEX ix_holdings_portfolio_id ON holdings (portfolio_id);

CREATE INDEX ix_holdings_security ON holdings (security_id);

CREATE TABLE participant_loans (
	participant_id VARCHAR(36) NOT NULL, 
	original_amount FLOAT NOT NULL, 
	outstanding_balance FLOAT NOT NULL, 
	interest_rate FLOAT NOT NULL, 
	term_months INTEGER NOT NULL, 
	payment_amount FLOAT NOT NULL, 
	issued_on DATE NOT NULL, 
	matures_on DATE NOT NULL, 
	loan_type VARCHAR(32) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(participant_id) REFERENCES participants (id) ON DELETE CASCADE
);

CREATE INDEX ix_participant_loans_participant_id ON participant_loans (participant_id);

CREATE TABLE rebalances (
	household_id VARCHAR(36) NOT NULL, 
	portfolio_id VARCHAR(36) NOT NULL, 
	approval_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	strategy_note TEXT, 
	status VARCHAR(24) NOT NULL, 
	max_drift FLOAT NOT NULL, 
	turnover_amount FLOAT NOT NULL, 
	estimated_tax_cost FLOAT NOT NULL, 
	estimated_trading_cost FLOAT NOT NULL, 
	cash_impact FLOAT NOT NULL, 
	created_by_id VARCHAR(36), 
	as_of TIMESTAMP WITH TIME ZONE, 
	executed_at TIMESTAMP WITH TIME ZONE, 
	is_simulated BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE, 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE SET NULL, 
	FOREIGN KEY(created_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_rebalance_household_status ON rebalances (household_id, status);

CREATE INDEX ix_rebalances_approval_id ON rebalances (approval_id);

CREATE INDEX ix_rebalances_household_id ON rebalances (household_id);

CREATE INDEX ix_rebalances_status ON rebalances (status);

CREATE TABLE recommendations (
	household_id VARCHAR(36) NOT NULL, 
	client_id VARCHAR(36), 
	approval_id VARCHAR(36), 
	title VARCHAR(200) NOT NULL, 
	category VARCHAR(48) NOT NULL, 
	severity VARCHAR(16) NOT NULL, 
	summary TEXT NOT NULL, 
	rationale TEXT NOT NULL, 
	suggested_action TEXT NOT NULL, 
	impact_amount FLOAT, 
	impact_label VARCHAR(120), 
	confidence FLOAT NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	generator VARCHAR(64) NOT NULL, 
	supporting_data JSON NOT NULL, 
	assumptions JSON NOT NULL, 
	limitations JSON NOT NULL, 
	entity_type VARCHAR(48), 
	entity_id VARCHAR(36), 
	as_of TIMESTAMP WITH TIME ZONE, 
	created_by_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(client_id) REFERENCES clients (id) ON DELETE SET NULL, 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE SET NULL, 
	FOREIGN KEY(created_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_recommendations_approval_id ON recommendations (approval_id);

CREATE INDEX ix_recommendations_category ON recommendations (category);

CREATE INDEX ix_recommendations_household_id ON recommendations (household_id);

CREATE INDEX ix_recommendations_household_status ON recommendations (household_id, status);

CREATE INDEX ix_recommendations_status ON recommendations (status);

CREATE TABLE rmds (
	client_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36) NOT NULL, 
	tax_year INTEGER NOT NULL, 
	prior_year_end_balance FLOAT NOT NULL, 
	life_expectancy_factor FLOAT NOT NULL, 
	required_amount FLOAT NOT NULL, 
	distributed_amount FLOAT NOT NULL, 
	deadline DATE NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	satisfied_by_qcd FLOAT NOT NULL, 
	method VARCHAR(120) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_rmds_client_id ON rmds (client_id);

CREATE INDEX ix_rmds_tax_year ON rmds (tax_year);

CREATE TABLE scenarios (
	goal_id VARCHAR(36), 
	household_id VARCHAR(36), 
	name VARCHAR(120) NOT NULL, 
	scenario_key VARCHAR(48) NOT NULL, 
	inputs JSON NOT NULL, 
	assumptions JSON NOT NULL, 
	result JSON NOT NULL, 
	method VARCHAR(96) NOT NULL, 
	is_baseline BOOLEAN NOT NULL, 
	run_at TIMESTAMP WITH TIME ZONE, 
	created_by_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(goal_id) REFERENCES goals (id) ON DELETE CASCADE, 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_scenarios_goal_id ON scenarios (goal_id);

CREATE INDEX ix_scenarios_household_id ON scenarios (household_id);

CREATE TABLE tax_opportunities (
	household_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36), 
	security_id VARCHAR(36), 
	opportunity_type VARCHAR(48) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	estimated_benefit FLOAT NOT NULL, 
	tax_year INTEGER NOT NULL, 
	severity VARCHAR(16) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	deadline DATE, 
	method VARCHAR(120) NOT NULL, 
	assumptions JSON NOT NULL, 
	supporting_data JSON NOT NULL, 
	as_of TIMESTAMP WITH TIME ZONE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE SET NULL, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE SET NULL
);

CREATE INDEX ix_tax_opportunities_household_id ON tax_opportunities (household_id);

CREATE INDEX ix_tax_opportunities_opportunity_type ON tax_opportunities (opportunity_type);

CREATE INDEX ix_tax_opportunities_status ON tax_opportunities (status);

CREATE INDEX ix_tax_opps_household_status ON tax_opportunities (household_id, status);

CREATE TABLE transactions (
	account_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36), 
	transaction_type VARCHAR(32) NOT NULL, 
	quantity FLOAT, 
	price FLOAT, 
	amount FLOAT NOT NULL, 
	fees FLOAT NOT NULL, 
	trade_date DATE NOT NULL, 
	settle_date DATE, 
	description TEXT, 
	realized_gain FLOAT, 
	is_long_term BOOLEAN, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE SET NULL
);

CREATE INDEX ix_transactions_account_date ON transactions (account_id, trade_date);

CREATE INDEX ix_transactions_account_id ON transactions (account_id);

CREATE INDEX ix_transactions_trade_date ON transactions (trade_date);

CREATE INDEX ix_transactions_transaction_type ON transactions (transaction_type);

CREATE TABLE trusts (
	household_id VARCHAR(36) NOT NULL, 
	estate_plan_id VARCHAR(36), 
	account_id VARCHAR(36), 
	name VARCHAR(160) NOT NULL, 
	trust_type VARCHAR(48) NOT NULL, 
	grantor VARCHAR(120) NOT NULL, 
	trustee VARCHAR(120) NOT NULL, 
	successor_trustee VARCHAR(120), 
	funded_amount FLOAT NOT NULL, 
	is_funded BOOLEAN NOT NULL, 
	established_on DATE, 
	situs VARCHAR(80), 
	distribution_standard VARCHAR(160), 
	status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(estate_plan_id) REFERENCES estate_plans (id) ON DELETE SET NULL, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE SET NULL
);

CREATE INDEX ix_trusts_household_id ON trusts (household_id);

CREATE TABLE beneficiaries (
	household_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36), 
	trust_id VARCHAR(36), 
	approval_id VARCHAR(36), 
	full_name VARCHAR(160) NOT NULL, 
	relationship_type VARCHAR(48) NOT NULL, 
	designation VARCHAR(24) NOT NULL, 
	percentage FLOAT NOT NULL, 
	birth_date DATE, 
	is_charity BOOLEAN NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	pending_percentage FLOAT, 
	last_confirmed_on DATE, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(trust_id) REFERENCES trusts (id) ON DELETE SET NULL, 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE SET NULL
);

CREATE INDEX ix_beneficiaries_account_id ON beneficiaries (account_id);

CREATE INDEX ix_beneficiaries_approval_id ON beneficiaries (approval_id);

CREATE INDEX ix_beneficiaries_household_id ON beneficiaries (household_id);

CREATE INDEX ix_beneficiary_account ON beneficiaries (account_id, designation);

CREATE TABLE compliance_tests (
	plan_id VARCHAR(36) NOT NULL, 
	test_type VARCHAR(48) NOT NULL, 
	tax_year INTEGER NOT NULL, 
	hce_value FLOAT, 
	nhce_value FLOAT, 
	threshold FLOAT, 
	result VARCHAR(24) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	due_date DATE, 
	completed_on DATE, 
	corrective_action TEXT, 
	evidence_document_id VARCHAR(36), 
	method VARCHAR(120) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(evidence_document_id) REFERENCES documents (id) ON DELETE SET NULL
);

CREATE INDEX ix_compliance_tests_plan_id ON compliance_tests (plan_id);

CREATE INDEX ix_compliance_tests_test_type ON compliance_tests (test_type);

CREATE INDEX ix_comptest_plan_year ON compliance_tests (plan_id, tax_year);

CREATE TABLE distribution_requests (
	household_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36) NOT NULL, 
	trust_id VARCHAR(36), 
	approval_id VARCHAR(36), 
	requested_by VARCHAR(120) NOT NULL, 
	beneficiary_name VARCHAR(160) NOT NULL, 
	amount FLOAT NOT NULL, 
	purpose VARCHAR(200) NOT NULL, 
	distribution_type VARCHAR(48) NOT NULL, 
	requested_on DATE NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	tax_withholding FLOAT NOT NULL, 
	notes TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(trust_id) REFERENCES trusts (id) ON DELETE SET NULL, 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE SET NULL
);

CREATE INDEX ix_distribution_requests_approval_id ON distribution_requests (approval_id);

CREATE INDEX ix_distribution_requests_household_id ON distribution_requests (household_id);

CREATE TABLE document_requests (
	household_id VARCHAR(36) NOT NULL, 
	requested_by_id VARCHAR(36), 
	title VARCHAR(200) NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	reason TEXT, 
	due_date DATE, 
	status VARCHAR(24) NOT NULL, 
	fulfilled_document_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(requested_by_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(fulfilled_document_id) REFERENCES documents (id) ON DELETE SET NULL
);

CREATE INDEX ix_document_requests_household_id ON document_requests (household_id);

CREATE TABLE document_shares (
	document_id VARCHAR(36) NOT NULL, 
	shared_with_id VARCHAR(36), 
	shared_with_label VARCHAR(160) NOT NULL, 
	permission VARCHAR(16) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	revoked BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE, 
	FOREIGN KEY(shared_with_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_document_shares_document_id ON document_shares (document_id);

CREATE TABLE document_versions (
	document_id VARCHAR(36) NOT NULL, 
	version INTEGER NOT NULL, 
	storage_key VARCHAR(512), 
	size_bytes INTEGER NOT NULL, 
	checksum VARCHAR(64), 
	uploaded_by_id VARCHAR(36), 
	change_note VARCHAR(255), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE, 
	FOREIGN KEY(uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_document_versions_document_id ON document_versions (document_id);

CREATE INDEX ix_docversion_document ON document_versions (document_id, version);

CREATE TABLE fiduciary_reviews (
	plan_id VARCHAR(36) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	review_period VARCHAR(32) NOT NULL, 
	held_on DATE NOT NULL, 
	attendees JSON NOT NULL, 
	agenda JSON NOT NULL, 
	minutes TEXT, 
	decisions JSON NOT NULL, 
	funds_on_watch INTEGER NOT NULL, 
	ips_compliant BOOLEAN NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	evidence_document_id VARCHAR(36), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE CASCADE, 
	FOREIGN KEY(evidence_document_id) REFERENCES documents (id) ON DELETE SET NULL
);

CREATE INDEX ix_fiduciary_reviews_plan_id ON fiduciary_reviews (plan_id);

CREATE TABLE grants (
	daf_id VARCHAR(36) NOT NULL, 
	charity_id VARCHAR(36) NOT NULL, 
	amount FLOAT NOT NULL, 
	granted_on DATE NOT NULL, 
	purpose VARCHAR(200), 
	is_recurring BOOLEAN NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	impact_note TEXT, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(daf_id) REFERENCES dafs (id) ON DELETE CASCADE, 
	FOREIGN KEY(charity_id) REFERENCES charities (id) ON DELETE CASCADE
);

CREATE INDEX ix_grants_daf_date ON grants (daf_id, granted_on);

CREATE INDEX ix_grants_daf_id ON grants (daf_id);

CREATE TABLE messages (
	thread_id VARCHAR(36) NOT NULL, 
	sender_id VARCHAR(36), 
	sender_name VARCHAR(160) NOT NULL, 
	sender_role VARCHAR(48) NOT NULL, 
	body TEXT NOT NULL, 
	sent_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	read_at TIMESTAMP WITH TIME ZONE, 
	attachment_document_id VARCHAR(36), 
	attachment_name VARCHAR(255), 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(thread_id) REFERENCES message_threads (id) ON DELETE CASCADE, 
	FOREIGN KEY(sender_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(attachment_document_id) REFERENCES documents (id) ON DELETE SET NULL
);

CREATE INDEX ix_messages_thread_id ON messages (thread_id);

CREATE INDEX ix_messages_thread_sent ON messages (thread_id, sent_at);

CREATE TABLE rebalance_trades (
	rebalance_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36) NOT NULL, 
	side VARCHAR(8) NOT NULL, 
	quantity FLOAT NOT NULL, 
	estimated_price FLOAT NOT NULL, 
	estimated_amount FLOAT NOT NULL, 
	realized_gain FLOAT NOT NULL, 
	tax_impact FLOAT NOT NULL, 
	rationale VARCHAR(255), 
	status VARCHAR(24) NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(rebalance_id) REFERENCES rebalances (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE CASCADE
);

CREATE INDEX ix_rebalance_trades_rebalance_id ON rebalance_trades (rebalance_id);

CREATE TABLE tax_lots (
	holding_id VARCHAR(36) NOT NULL, 
	quantity FLOAT NOT NULL, 
	cost_per_share FLOAT NOT NULL, 
	acquired_on DATE NOT NULL, 
	lot_method VARCHAR(16) NOT NULL, 
	is_open BOOLEAN NOT NULL, 
	washed BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(holding_id) REFERENCES holdings (id) ON DELETE CASCADE
);

CREATE INDEX ix_tax_lots_acquired ON tax_lots (acquired_on);

CREATE INDEX ix_tax_lots_holding_id ON tax_lots (holding_id);

CREATE TABLE wash_sale_windows (
	account_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36) NOT NULL, 
	trigger_transaction_id VARCHAR(36), 
	window_start DATE NOT NULL, 
	window_end DATE NOT NULL, 
	reason VARCHAR(160) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE CASCADE, 
	FOREIGN KEY(trigger_transaction_id) REFERENCES transactions (id) ON DELETE SET NULL
);

CREATE INDEX ix_wash_account_security ON wash_sale_windows (account_id, security_id);

CREATE INDEX ix_wash_sale_windows_account_id ON wash_sale_windows (account_id);

CREATE TABLE harvests (
	household_id VARCHAR(36) NOT NULL, 
	account_id VARCHAR(36) NOT NULL, 
	security_id VARCHAR(36) NOT NULL, 
	tax_lot_id VARCHAR(36), 
	replacement_security_id VARCHAR(36), 
	approval_id VARCHAR(36), 
	quantity FLOAT NOT NULL, 
	cost_basis FLOAT NOT NULL, 
	market_value FLOAT NOT NULL, 
	unrealized_loss FLOAT NOT NULL, 
	holding_period VARCHAR(16) NOT NULL, 
	estimated_tax_benefit FLOAT NOT NULL, 
	wash_sale_risk VARCHAR(16) NOT NULL, 
	wash_sale_window_ends DATE, 
	status VARCHAR(24) NOT NULL, 
	tax_year INTEGER NOT NULL, 
	notes TEXT, 
	executed_at TIMESTAMP WITH TIME ZONE, 
	is_simulated BOOLEAN NOT NULL, 
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(household_id) REFERENCES households (id) ON DELETE CASCADE, 
	FOREIGN KEY(account_id) REFERENCES accounts (id) ON DELETE CASCADE, 
	FOREIGN KEY(security_id) REFERENCES securities (id) ON DELETE CASCADE, 
	FOREIGN KEY(tax_lot_id) REFERENCES tax_lots (id) ON DELETE SET NULL, 
	FOREIGN KEY(replacement_security_id) REFERENCES securities (id) ON DELETE SET NULL, 
	FOREIGN KEY(approval_id) REFERENCES approvals (id) ON DELETE SET NULL
);

CREATE INDEX ix_harvests_approval_id ON harvests (approval_id);

CREATE INDEX ix_harvests_household_id ON harvests (household_id);

CREATE INDEX ix_harvests_household_status ON harvests (household_id, status);

CREATE INDEX ix_harvests_status ON harvests (status);
COMMIT;

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- The FastAPI service connects with the service role and enforces
-- authorisation itself (see app/core/deps.py), so RLS is not required for the
-- API path. Enable it if any client will query Supabase directly — see
-- supabase/policies.sql.
-- ---------------------------------------------------------------------------
