"""Goals, scenarios and recommendations."""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import Boolean, Date, DateTime, Float, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import BaseModel


class Goal(BaseModel):
    __tablename__ = "goals"
    __table_args__ = (Index("ix_goals_household_type", "household_id", "goal_type"),)

    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    client_id: Mapped[str | None] = mapped_column(ForeignKey("clients.id", ondelete="SET NULL"))
    name: Mapped[str] = mapped_column(String(160))
    goal_type: Mapped[str] = mapped_column(String(32), index=True)
    description: Mapped[str | None] = mapped_column(Text())
    target_amount: Mapped[float] = mapped_column(Float)
    current_amount: Mapped[float] = mapped_column(Float, default=0.0)
    target_date: Mapped[date] = mapped_column(Date())
    monthly_contribution: Mapped[float] = mapped_column(Float, default=0.0)
    expected_return: Mapped[float] = mapped_column(Float, default=0.06)
    inflation_rate: Mapped[float] = mapped_column(Float, default=0.025)
    priority: Mapped[str] = mapped_column(String(16), default="high")
    status: Mapped[str] = mapped_column(String(24), default="on_track")
    owner_label: Mapped[str | None] = mapped_column(String(96))

    linked_accounts: Mapped[list["GoalAccount"]] = relationship(back_populates="goal", cascade="all, delete-orphan")
    scenarios: Mapped[list["Scenario"]] = relationship(back_populates="goal", cascade="all, delete-orphan")


class GoalAccount(BaseModel):
    __tablename__ = "goal_accounts"
    __table_args__ = (UniqueConstraint("goal_id", "account_id", name="uq_goal_account"),)

    goal_id: Mapped[str] = mapped_column(ForeignKey("goals.id", ondelete="CASCADE"), index=True)
    account_id: Mapped[str] = mapped_column(ForeignKey("accounts.id", ondelete="CASCADE"), index=True)
    allocation_percent: Mapped[float] = mapped_column(Float, default=1.0)

    goal: Mapped[Goal] = relationship(back_populates="linked_accounts")


class Scenario(BaseModel):
    """A what-if run. Scenarios never alter books of record (§4)."""

    __tablename__ = "scenarios"

    goal_id: Mapped[str | None] = mapped_column(ForeignKey("goals.id", ondelete="CASCADE"), index=True)
    household_id: Mapped[str | None] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(120))
    scenario_key: Mapped[str] = mapped_column(String(48), default="base_case")
    inputs: Mapped[dict] = mapped_column(default=dict)
    assumptions: Mapped[dict] = mapped_column(default=dict)
    result: Mapped[dict] = mapped_column(default=dict)
    method: Mapped[str] = mapped_column(String(96), default="deterministic_future_value")
    is_baseline: Mapped[bool] = mapped_column(Boolean, default=False)
    run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by_id: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))

    goal: Mapped[Goal | None] = relationship(back_populates="scenarios")


class Recommendation(BaseModel):
    """Advice generated by deterministic rules, always human-reviewed."""

    __tablename__ = "recommendations"
    __table_args__ = (Index("ix_recommendations_household_status", "household_id", "status"),)

    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    client_id: Mapped[str | None] = mapped_column(ForeignKey("clients.id", ondelete="SET NULL"))
    approval_id: Mapped[str | None] = mapped_column(ForeignKey("approvals.id", ondelete="SET NULL"), index=True)
    title: Mapped[str] = mapped_column(String(200))
    category: Mapped[str] = mapped_column(String(48), index=True)
    severity: Mapped[str] = mapped_column(String(16), default="medium")
    summary: Mapped[str] = mapped_column(Text())
    rationale: Mapped[str] = mapped_column(Text())
    suggested_action: Mapped[str] = mapped_column(Text())
    impact_amount: Mapped[float | None] = mapped_column(Float)
    impact_label: Mapped[str | None] = mapped_column(String(120))
    confidence: Mapped[float] = mapped_column(Float, default=0.8)
    status: Mapped[str] = mapped_column(String(24), default="draft", index=True)
    source: Mapped[str] = mapped_column(String(64), default="wealthagent_rules")
    generator: Mapped[str] = mapped_column(String(64), default="mock")
    supporting_data: Mapped[dict] = mapped_column(default=dict)
    assumptions: Mapped[list] = mapped_column(default=list)
    limitations: Mapped[list] = mapped_column(default=list)
    entity_type: Mapped[str | None] = mapped_column(String(48))
    entity_id: Mapped[str | None] = mapped_column(String(36))
    as_of: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by_id: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))


class Task(BaseModel):
    __tablename__ = "tasks"
    __table_args__ = (Index("ix_tasks_assignee_status", "assignee_id", "status"),)

    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str | None] = mapped_column(Text())
    assignee_id: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), index=True)
    household_id: Mapped[str | None] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    category: Mapped[str] = mapped_column(String(48), default="service")
    priority: Mapped[str] = mapped_column(String(16), default="medium")
    status: Mapped[str] = mapped_column(String(24), default="open")
    due_date: Mapped[date | None] = mapped_column(Date())
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    sla_days: Mapped[int | None] = mapped_column(Integer)
