"""Emit the Postgres DDL from the mappers.

Run from `backend/`:

    python -m app.seeds.emit_schema

Generating the SQL from the ORM rather than maintaining it by hand means
supabase/schema.sql cannot drift away from the models.
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app import models

HEADER = """-- ===========================================================================
-- Nexgile WealthAgent — Supabase / PostgreSQL schema
--
-- Generated from the SQLAlchemy models in backend/app/models so this file and
-- the ORM cannot drift apart. Regenerate with:
--
--     python -m app.seeds.emit_schema        (from backend/)
--
-- Apply it in the Supabase SQL editor, or:
--     psql "$DATABASE_URL" -f supabase/schema.sql
--
-- Then load the demonstration dataset:
--     DATABASE_URL="postgresql://..." python seed.py
--
-- Conventions
--   * Primary keys are UUID strings generated by the application.
--   * Every table carries created_at / updated_at.
--   * Foreign keys use ON DELETE CASCADE for owned records and SET NULL for
--     references that should survive the parent being removed.
--   * Indexes back every foreign key and every column the API filters on.
-- ===========================================================================

BEGIN;

"""

FOOTER = """
COMMIT;

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- The FastAPI service connects with the service role and enforces
-- authorisation itself (see app/core/deps.py), so RLS is not required for the
-- API path. Enable it if any client will query Supabase directly — see
-- supabase/policies.sql.
-- ---------------------------------------------------------------------------
"""

OUTPUT = Path(__file__).resolve().parents[3] / "supabase" / "schema.sql"


def emit() -> Path:
    dialect = postgresql.dialect()
    statements: list[str] = []

    for table in models.Base.metadata.sorted_tables:
        statements.append(f"{str(CreateTable(table).compile(dialect=dialect)).strip()};")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            statements.append(f"{str(CreateIndex(index).compile(dialect=dialect)).strip()};")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER + "\n\n".join(statements) + FOOTER, encoding="utf-8")
    return OUTPUT


if __name__ == "__main__":
    path = emit()
    print(f"Wrote {len(models.Base.metadata.sorted_tables)} tables to {path}")
