"""Household blueprints for the demonstration dataset.

Every figure below is fictional. Account balances are *derived* from the
holdings and cash defined here, so the dataset is internally consistent by
construction rather than by transcription.

`target_value` is the invested market value the generator solves for; the
weights inside `holdings` must sum to 1.0. `gain` is the unrealised gain as a
fraction of cost, which sets the cost basis (a negative gain creates a genuine
tax-loss harvesting candidate).
"""

from __future__ import annotations

HOUSEHOLDS: list[dict] = [
    {
        "key": "johnson",
        "name": "Johnson Family",
        "segment": "private_client",
        "risk_profile": "moderate_growth",
        "city": "Portland",
        "state": "OR",
        "since": "2014-03-11",
        "benchmark": "GLOBAL_60_40",
        "strategy": "Balanced Growth",
        "notes": "Multi-generational relationship. Priorities: retirement income, education funding and a legacy gift.",
        "principals": [
            {
                "full_name": "Sarah Johnson",
                "birth_date": "1974-06-18",
                "retirement_age": 65,
                "filing_status": "married_joint",
                "marginal_tax_rate": 0.35,
                "ltcg_tax_rate": 0.20,
                "state_tax_rate": 0.0495,
                "annual_income": 685_000.0,
                "annual_savings": 168_000.0,
                "risk_tolerance": "moderate_growth",
                "is_demo_user": True,
            },
            {
                "full_name": "David Johnson",
                "birth_date": "1972-11-02",
                "retirement_age": 66,
                "filing_status": "married_joint",
                "marginal_tax_rate": 0.35,
                "ltcg_tax_rate": 0.20,
                "state_tax_rate": 0.0495,
                "annual_income": 240_000.0,
                "annual_savings": 42_000.0,
                "risk_tolerance": "moderate",
            },
        ],
        "members": [
            {"full_name": "Maya Johnson", "relationship_type": "child", "birth_date": "2010-04-22", "is_dependent": True},
            {"full_name": "Theo Johnson", "relationship_type": "child", "birth_date": "2013-09-08", "is_dependent": True},
            {"full_name": "Ruth Aldridge", "relationship_type": "parent", "birth_date": "1948-02-14", "is_dependent": False},
        ],
        "accounts": [
            {
                "name": "Joint Brokerage",
                "account_type": "brokerage",
                "subtype": "taxable_joint",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Meridian Trust & Custody",
                "target_value": 8_450_000.0,
                "cash": 612_000.0,
                "opened_on": "2014-04-02",
                "holdings": [
                    {"symbol": "VTI", "weight": 0.160, "gain": 0.58},
                    {"symbol": "VOO", "weight": 0.100, "gain": 0.44},
                    {"symbol": "NVDA", "weight": 0.290, "gain": 3.10},
                    {"symbol": "MSFT", "weight": 0.082, "gain": 0.91},
                    {"symbol": "VXUS", "weight": 0.096, "gain": 0.07},
                    {"symbol": "EFA", "weight": 0.058, "gain": -0.14},
                    {"symbol": "VWO", "weight": 0.040, "gain": -0.11},
                    {"symbol": "MUB", "weight": 0.084, "gain": -0.05},
                    {"symbol": "VCIT", "weight": 0.052, "gain": -0.03},
                    {"symbol": "GLD", "weight": 0.018, "gain": 0.36},
                    {"symbol": "VNQ", "weight": 0.020, "gain": -0.09},
                ],
            },
            {
                "name": "Sarah — Rollover IRA",
                "account_type": "retirement",
                "subtype": "rollover_ira",
                "tax_treatment": "tax_deferred",
                "registration": "individual",
                "custodian": "Meridian Trust & Custody",
                "target_value": 4_180_000.0,
                "cash": 96_000.0,
                "opened_on": "2011-08-19",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.300, "gain": 0.62},
                    {"symbol": "SCHG", "weight": 0.140, "gain": 0.71},
                    {"symbol": "IXUS", "weight": 0.170, "gain": 0.12},
                    {"symbol": "BND", "weight": 0.230, "gain": -0.06},
                    {"symbol": "VCIT", "weight": 0.090, "gain": -0.02},
                    {"symbol": "QAI", "weight": 0.070, "gain": 0.09},
                ],
            },
            {
                "name": "Sarah — Roth IRA",
                "account_type": "retirement",
                "subtype": "roth_ira",
                "tax_treatment": "tax_free",
                "registration": "individual",
                "custodian": "Meridian Trust & Custody",
                "target_value": 1_240_000.0,
                "cash": 18_500.0,
                "opened_on": "2009-01-14",
                "holdings": [
                    {"symbol": "SCHG", "weight": 0.420, "gain": 1.24},
                    {"symbol": "AVUV", "weight": 0.230, "gain": 0.38},
                    {"symbol": "VXUS", "weight": 0.220, "gain": 0.16},
                    {"symbol": "PSP", "weight": 0.130, "gain": -0.18},
                ],
            },
            {
                "name": "David — 401(k)",
                "account_type": "retirement",
                "subtype": "401k",
                "tax_treatment": "tax_deferred",
                "registration": "individual",
                "custodian": "Ironbridge Retirement Services",
                "target_value": 2_310_000.0,
                "cash": 24_000.0,
                "opened_on": "2008-06-01",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.380, "gain": 0.55},
                    {"symbol": "VXUS", "weight": 0.210, "gain": 0.10},
                    {"symbol": "BND", "weight": 0.290, "gain": -0.05},
                    {"symbol": "VNQ", "weight": 0.120, "gain": -0.07},
                ],
            },
            {
                "name": "Maya — 529 Education Savings",
                "account_type": "education",
                "subtype": "529",
                "tax_treatment": "tax_free",
                "registration": "custodial",
                "custodian": "Harborline Securities",
                "target_value": 268_000.0,
                "cash": 9_400.0,
                "opened_on": "2011-05-30",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.520, "gain": 0.47},
                    {"symbol": "IXUS", "weight": 0.230, "gain": 0.11},
                    {"symbol": "BND", "weight": 0.250, "gain": -0.04},
                ],
            },
            {
                "name": "Theo — 529 Education Savings",
                "account_type": "education",
                "subtype": "529",
                "tax_treatment": "tax_free",
                "registration": "custodial",
                "custodian": "Harborline Securities",
                "target_value": 186_000.0,
                "cash": 6_100.0,
                "opened_on": "2014-02-11",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.560, "gain": 0.41},
                    {"symbol": "IXUS", "weight": 0.240, "gain": 0.09},
                    {"symbol": "BND", "weight": 0.200, "gain": -0.04},
                ],
            },
            {
                "name": "Johnson Legacy Trust",
                "account_type": "trust",
                "subtype": "irrevocable_trust",
                "tax_treatment": "taxable",
                "registration": "trust",
                "custodian": "Northmoor Private Bank",
                "target_value": 3_120_000.0,
                "cash": 140_000.0,
                "opened_on": "2019-10-04",
                "holdings": [
                    {"symbol": "VTI", "weight": 0.320, "gain": 0.29},
                    {"symbol": "VTEB", "weight": 0.310, "gain": -0.04},
                    {"symbol": "IXUS", "weight": 0.180, "gain": 0.08},
                    {"symbol": "QAI", "weight": 0.110, "gain": 0.06},
                    {"symbol": "GLD", "weight": 0.080, "gain": 0.31},
                ],
            },
            {
                "name": "Cascade Everyday Checking",
                "account_type": "banking",
                "subtype": "checking",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "cash_only": 184_500.0,
                "opened_on": "2012-01-09",
            },
            {
                "name": "Cascade High-Yield Savings",
                "account_type": "banking",
                "subtype": "savings",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "cash_only": 412_000.0,
                "opened_on": "2016-07-21",
            },
            {
                "name": "Residence Mortgage",
                "account_type": "mortgage",
                "subtype": "primary_residence",
                "tax_treatment": "n/a",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "liability": 3_218_000.0,
                "interest_rate": 0.0425,
                "minimum_payment": 18_240.0,
                "opened_on": "2019-06-14",
            },
            {
                "name": "Platinum Card",
                "account_type": "credit",
                "subtype": "revolving",
                "tax_treatment": "n/a",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "liability": 41_800.0,
                "interest_rate": 0.1974,
                "minimum_payment": 1_250.0,
                "external": True,
                "opened_on": "2015-03-02",
            },
        ],
        "targets": {
            "us_equity": 0.40,
            "intl_equity": 0.18,
            "fixed_income": 0.24,
            "cash": 0.06,
            "alternatives": 0.06,
            "real_assets": 0.06,
        },
        "goals": [
            {
                "name": "Retirement at 65",
                "goal_type": "retirement",
                "target_amount": 15_500_000.0,
                "current_from_accounts": ["Sarah — Rollover IRA", "Sarah — Roth IRA", "David — 401(k)", "Joint Brokerage"],
                "current_ratio": 0.55,
                "target_date": "2039-06-01",
                "monthly_contribution": 14_000.0,
                "expected_return": 0.062,
                "inflation_rate": 0.025,
                "priority": "high",
                "owner_label": "Sarah & David",
                "description": "Replace 80% of pre-retirement income with a portfolio that supports a 35-year retirement.",
            },
            {
                "name": "Maya — University Fund",
                "goal_type": "education",
                "target_amount": 420_000.0,
                "current_from_accounts": ["Maya — 529 Education Savings"],
                "current_ratio": 1.0,
                "target_date": "2028-08-15",
                "monthly_contribution": 4_500.0,
                "expected_return": 0.048,
                "inflation_rate": 0.052,
                "priority": "high",
                "owner_label": "Maya",
                "description": "Four years of private university tuition, room and board.",
            },
            {
                "name": "Theo — University Fund",
                "goal_type": "education",
                "target_amount": 560_000.0,
                "current_from_accounts": ["Theo — 529 Education Savings"],
                "current_ratio": 1.0,
                "target_date": "2031-08-15",
                "monthly_contribution": 4_800.0,
                "expected_return": 0.050,
                "inflation_rate": 0.052,
                "priority": "high",
                "owner_label": "Theo",
                "description": "Four years of private university tuition, room and board.",
            },
            {
                "name": "Coastal Property",
                "goal_type": "home",
                "target_amount": 2_200_000.0,
                "current_from_accounts": ["Cascade High-Yield Savings"],
                "current_ratio": 1.0,
                "target_date": "2030-05-01",
                "monthly_contribution": 14_000.0,
                "expected_return": 0.042,
                "inflation_rate": 0.035,
                "priority": "medium",
                "owner_label": "Sarah & David",
                "description": "Second home on the Oregon coast, purchased outright.",
            },
            {
                "name": "Family Legacy",
                "goal_type": "legacy",
                "target_amount": 6_000_000.0,
                "current_from_accounts": ["Johnson Legacy Trust"],
                "current_ratio": 1.0,
                "target_date": "2044-01-01",
                "monthly_contribution": 6_000.0,
                "expected_return": 0.058,
                "inflation_rate": 0.025,
                "priority": "medium",
                "owner_label": "Johnson Legacy Trust",
                "description": "Provision for the next generation and the family foundation.",
            },
        ],
    },
    {
        "key": "okonkwo",
        "name": "Okonkwo Household",
        "segment": "private_client",
        "risk_profile": "growth",
        "city": "Austin",
        "state": "TX",
        "since": "2018-09-04",
        "benchmark": "GROWTH_80_20",
        "strategy": "Global Growth",
        "notes": "Founder liquidity event in 2023. Focus on diversification away from a concentrated position.",
        "principals": [
            {
                "full_name": "Chidi Okonkwo",
                "birth_date": "1981-03-27",
                "retirement_age": 60,
                "filing_status": "married_joint",
                "marginal_tax_rate": 0.37,
                "ltcg_tax_rate": 0.20,
                "state_tax_rate": 0.0,
                "annual_income": 1_240_000.0,
                "annual_savings": 420_000.0,
                "risk_tolerance": "growth",
            },
            {
                "full_name": "Adaeze Okonkwo",
                "birth_date": "1983-12-05",
                "retirement_age": 60,
                "filing_status": "married_joint",
                "marginal_tax_rate": 0.37,
                "ltcg_tax_rate": 0.20,
                "state_tax_rate": 0.0,
                "annual_income": 310_000.0,
                "annual_savings": 88_000.0,
                "risk_tolerance": "moderate_growth",
            },
        ],
        "members": [
            {"full_name": "Ngozi Okonkwo", "relationship_type": "child", "birth_date": "2016-07-19", "is_dependent": True},
        ],
        "accounts": [
            {
                "name": "Okonkwo Joint Brokerage",
                "account_type": "brokerage",
                "subtype": "taxable_joint",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Harborline Securities",
                "target_value": 9_820_000.0,
                "cash": 1_140_000.0,
                "opened_on": "2018-10-02",
                "holdings": [
                    {"symbol": "NVDA", "weight": 0.268, "gain": 5.40},
                    {"symbol": "VTI", "weight": 0.196, "gain": 0.33},
                    {"symbol": "SCHG", "weight": 0.148, "gain": 0.52},
                    {"symbol": "VXUS", "weight": 0.118, "gain": 0.06},
                    {"symbol": "VWO", "weight": 0.052, "gain": -0.13},
                    {"symbol": "MUB", "weight": 0.098, "gain": -0.04},
                    {"symbol": "PSP", "weight": 0.062, "gain": -0.16},
                    {"symbol": "GLD", "weight": 0.058, "gain": 0.28},
                ],
            },
            {
                "name": "Chidi — SEP IRA",
                "account_type": "retirement",
                "subtype": "sep_ira",
                "tax_treatment": "tax_deferred",
                "registration": "individual",
                "custodian": "Harborline Securities",
                "target_value": 1_940_000.0,
                "cash": 42_000.0,
                "opened_on": "2019-02-20",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.400, "gain": 0.48},
                    {"symbol": "IXUS", "weight": 0.220, "gain": 0.09},
                    {"symbol": "AGG", "weight": 0.240, "gain": -0.05},
                    {"symbol": "QAI", "weight": 0.140, "gain": 0.07},
                ],
            },
            {
                "name": "Ngozi — 529 Plan",
                "account_type": "education",
                "subtype": "529",
                "tax_treatment": "tax_free",
                "registration": "custodial",
                "custodian": "Harborline Securities",
                "target_value": 142_000.0,
                "cash": 4_800.0,
                "opened_on": "2017-01-11",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.640, "gain": 0.39},
                    {"symbol": "BND", "weight": 0.360, "gain": -0.03},
                ],
            },
            {
                "name": "Harborline Cash Management",
                "account_type": "banking",
                "subtype": "checking",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Harborline Securities",
                "cash_only": 386_000.0,
                "opened_on": "2018-10-02",
            },
            {
                "name": "Residence Mortgage",
                "account_type": "mortgage",
                "subtype": "primary_residence",
                "tax_treatment": "n/a",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "liability": 1_640_000.0,
                "interest_rate": 0.0538,
                "minimum_payment": 10_920.0,
                "opened_on": "2021-04-30",
            },
        ],
        "targets": {
            "us_equity": 0.44,
            "intl_equity": 0.20,
            "fixed_income": 0.18,
            "cash": 0.06,
            "alternatives": 0.06,
            "real_assets": 0.06,
        },
        "goals": [
            {
                "name": "Financial Independence at 60",
                "goal_type": "retirement",
                "target_amount": 22_000_000.0,
                "current_from_accounts": ["Okonkwo Joint Brokerage", "Chidi — SEP IRA"],
                "current_ratio": 0.70,
                "target_date": "2041-03-01",
                "monthly_contribution": 34_000.0,
                "expected_return": 0.065,
                "inflation_rate": 0.025,
                "priority": "high",
                "owner_label": "Chidi & Adaeze",
                "description": "Fund an early retirement with a 40-year horizon.",
            },
            {
                "name": "Ngozi — Education",
                "goal_type": "education",
                "target_amount": 640_000.0,
                "current_from_accounts": ["Ngozi — 529 Plan"],
                "current_ratio": 1.0,
                "target_date": "2034-08-15",
                "monthly_contribution": 1_800.0,
                "expected_return": 0.052,
                "inflation_rate": 0.052,
                "priority": "high",
                "owner_label": "Ngozi",
                "description": "Private university, four years.",
            },
            {
                "name": "Foundation Endowment",
                "goal_type": "legacy",
                "target_amount": 5_000_000.0,
                "current_from_accounts": [],
                "current_amount": 840_000.0,
                "target_date": "2038-01-01",
                "monthly_contribution": 12_000.0,
                "expected_return": 0.055,
                "inflation_rate": 0.025,
                "priority": "medium",
                "owner_label": "Okonkwo Family Foundation",
                "description": "Seed a perpetual family foundation focused on education access.",
            },
        ],
    },
    {
        "key": "lindqvist",
        "name": "Lindqvist Family Trust",
        "segment": "family_office",
        "risk_profile": "conservative_growth",
        "city": "Minneapolis",
        "state": "MN",
        "since": "2009-05-18",
        "benchmark": "CONSERVATIVE_30_70",
        "strategy": "Capital Preservation",
        "notes": "Third-generation family office. Distributions fund four beneficiary households.",
        "principals": [
            {
                "full_name": "Astrid Lindqvist",
                "birth_date": "1951-09-30",
                "retirement_age": 62,
                "filing_status": "single",
                "marginal_tax_rate": 0.32,
                "ltcg_tax_rate": 0.20,
                "state_tax_rate": 0.0785,
                "annual_income": 410_000.0,
                "annual_savings": 0.0,
                "risk_tolerance": "conservative",
            },
        ],
        "members": [
            {"full_name": "Erik Lindqvist", "relationship_type": "child", "birth_date": "1979-01-24", "is_dependent": False},
            {"full_name": "Sofia Lindqvist-Moreau", "relationship_type": "child", "birth_date": "1982-06-11", "is_dependent": False},
            {"full_name": "Nils Lindqvist", "relationship_type": "grandchild", "birth_date": "2009-03-03", "is_dependent": False},
        ],
        "accounts": [
            {
                "name": "Lindqvist Family Trust — Core",
                "account_type": "trust",
                "subtype": "irrevocable_trust",
                "tax_treatment": "taxable",
                "registration": "trust",
                "custodian": "Northmoor Private Bank",
                "target_value": 18_400_000.0,
                "cash": 1_820_000.0,
                "opened_on": "2009-06-01",
                "holdings": [
                    {"symbol": "VTI", "weight": 0.180, "gain": 0.94},
                    {"symbol": "BRK.B", "weight": 0.092, "gain": 1.66},
                    {"symbol": "JNJ", "weight": 0.058, "gain": 0.21},
                    {"symbol": "IXUS", "weight": 0.110, "gain": 0.14},
                    {"symbol": "VTEB", "weight": 0.246, "gain": -0.05},
                    {"symbol": "AGG", "weight": 0.152, "gain": -0.07},
                    {"symbol": "VCIT", "weight": 0.070, "gain": -0.02},
                    {"symbol": "QAI", "weight": 0.052, "gain": 0.05},
                    {"symbol": "GLD", "weight": 0.040, "gain": 0.42},
                ],
            },
            {
                "name": "Astrid — IRA",
                "account_type": "retirement",
                "subtype": "traditional_ira",
                "tax_treatment": "tax_deferred",
                "registration": "individual",
                "custodian": "Northmoor Private Bank",
                "target_value": 3_260_000.0,
                "cash": 128_000.0,
                "opened_on": "1996-04-15",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.260, "gain": 1.14},
                    {"symbol": "VXUS", "weight": 0.140, "gain": 0.18},
                    {"symbol": "BND", "weight": 0.380, "gain": -0.06},
                    {"symbol": "VCIT", "weight": 0.150, "gain": -0.03},
                    {"symbol": "SGOV", "weight": 0.070, "gain": 0.00},
                ],
            },
            {
                "name": "Northmoor Operating Account",
                "account_type": "banking",
                "subtype": "checking",
                "tax_treatment": "taxable",
                "registration": "trust",
                "custodian": "Northmoor Private Bank",
                "cash_only": 640_000.0,
                "opened_on": "2009-06-01",
            },
        ],
        "targets": {
            "us_equity": 0.26,
            "intl_equity": 0.12,
            "fixed_income": 0.42,
            "cash": 0.10,
            "alternatives": 0.05,
            "real_assets": 0.05,
        },
        "goals": [
            {
                "name": "Perpetual Trust Corpus",
                "goal_type": "legacy",
                "target_amount": 25_000_000.0,
                "current_from_accounts": ["Lindqvist Family Trust — Core"],
                "current_ratio": 1.0,
                "target_date": "2035-01-01",
                "monthly_contribution": 0.0,
                "expected_return": 0.048,
                "inflation_rate": 0.025,
                "priority": "high",
                "owner_label": "Lindqvist Family Trust",
                "description": "Preserve real purchasing power of the corpus while funding annual distributions.",
            },
            {
                "name": "Annual Beneficiary Distributions",
                "goal_type": "custom",
                "target_amount": 900_000.0,
                "current_from_accounts": ["Northmoor Operating Account"],
                "current_ratio": 1.0,
                "target_date": "2027-12-31",
                "monthly_contribution": 0.0,
                "expected_return": 0.038,
                "inflation_rate": 0.025,
                "priority": "high",
                "owner_label": "Trustee",
                "description": "Fund four beneficiary distributions annually from income, not corpus.",
            },
        ],
    },
    {
        "key": "delacroix",
        "name": "Delacroix Household",
        "segment": "wealth_management",
        "risk_profile": "moderate",
        "city": "Denver",
        "state": "CO",
        "since": "2021-02-08",
        "benchmark": "GLOBAL_60_40",
        "strategy": "Balanced",
        "notes": "Dual-income professionals building toward a first retirement milestone.",
        "principals": [
            {
                "full_name": "Camille Delacroix",
                "birth_date": "1986-08-14",
                "retirement_age": 67,
                "filing_status": "married_joint",
                "marginal_tax_rate": 0.24,
                "ltcg_tax_rate": 0.15,
                "state_tax_rate": 0.044,
                "annual_income": 268_000.0,
                "annual_savings": 54_000.0,
                "risk_tolerance": "moderate",
            },
        ],
        "members": [
            {"full_name": "Julien Delacroix", "relationship_type": "spouse", "birth_date": "1985-05-21", "is_dependent": False},
            {"full_name": "Elodie Delacroix", "relationship_type": "child", "birth_date": "2019-11-30", "is_dependent": True},
        ],
        "accounts": [
            {
                "name": "Delacroix Brokerage",
                "account_type": "brokerage",
                "subtype": "taxable_joint",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Harborline Securities",
                "target_value": 1_180_000.0,
                "cash": 62_000.0,
                "opened_on": "2021-03-01",
                "holdings": [
                    {"symbol": "VTI", "weight": 0.380, "gain": 0.31},
                    {"symbol": "VXUS", "weight": 0.200, "gain": 0.05},
                    {"symbol": "BND", "weight": 0.260, "gain": -0.05},
                    {"symbol": "EFA", "weight": 0.090, "gain": -0.12},
                    {"symbol": "VNQ", "weight": 0.070, "gain": -0.08},
                ],
            },
            {
                "name": "Camille — 401(k)",
                "account_type": "retirement",
                "subtype": "401k",
                "tax_treatment": "tax_deferred",
                "registration": "individual",
                "custodian": "Ironbridge Retirement Services",
                "target_value": 742_000.0,
                "cash": 8_200.0,
                "opened_on": "2012-09-04",
                "holdings": [
                    {"symbol": "VOO", "weight": 0.520, "gain": 0.44},
                    {"symbol": "IXUS", "weight": 0.220, "gain": 0.08},
                    {"symbol": "AGG", "weight": 0.260, "gain": -0.05},
                ],
            },
            {
                "name": "Camille — Roth IRA",
                "account_type": "retirement",
                "subtype": "roth_ira",
                "tax_treatment": "tax_free",
                "registration": "individual",
                "custodian": "Harborline Securities",
                "target_value": 214_000.0,
                "cash": 3_100.0,
                "opened_on": "2015-01-20",
                "holdings": [
                    {"symbol": "SCHG", "weight": 0.560, "gain": 0.68},
                    {"symbol": "AVUV", "weight": 0.440, "gain": 0.22},
                ],
            },
            {
                "name": "Elodie — 529 Plan",
                "account_type": "education",
                "subtype": "529",
                "tax_treatment": "tax_free",
                "registration": "custodial",
                "custodian": "Harborline Securities",
                "target_value": 48_000.0,
                "cash": 1_600.0,
                "opened_on": "2020-02-14",
                "holdings": [{"symbol": "VOO", "weight": 0.700, "gain": 0.34}, {"symbol": "BND", "weight": 0.300, "gain": -0.03}],
            },
            {
                "name": "Everyday Checking",
                "account_type": "banking",
                "subtype": "checking",
                "tax_treatment": "taxable",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "cash_only": 74_000.0,
                "opened_on": "2019-08-08",
            },
            {
                "name": "Residence Mortgage",
                "account_type": "mortgage",
                "subtype": "primary_residence",
                "tax_treatment": "n/a",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "liability": 612_000.0,
                "interest_rate": 0.0312,
                "minimum_payment": 3_180.0,
                "opened_on": "2020-01-17",
            },
            {
                "name": "Rewards Card",
                "account_type": "credit",
                "subtype": "revolving",
                "tax_treatment": "n/a",
                "registration": "joint_tenants",
                "custodian": "Cascade National Bank",
                "liability": 8_400.0,
                "interest_rate": 0.2149,
                "minimum_payment": 320.0,
                "external": True,
                "opened_on": "2019-08-08",
            },
        ],
        "targets": {
            "us_equity": 0.42,
            "intl_equity": 0.18,
            "fixed_income": 0.28,
            "cash": 0.05,
            "alternatives": 0.03,
            "real_assets": 0.04,
        },
        "goals": [
            {
                "name": "Retirement at 67",
                "goal_type": "retirement",
                "target_amount": 6_400_000.0,
                "current_from_accounts": ["Camille — 401(k)", "Camille — Roth IRA", "Delacroix Brokerage"],
                "current_ratio": 0.80,
                "target_date": "2053-08-01",
                "monthly_contribution": 4_500.0,
                "expected_return": 0.060,
                "inflation_rate": 0.025,
                "priority": "high",
                "owner_label": "Camille & Julien",
                "description": "Comfortable retirement at full Social Security age.",
            },
            {
                "name": "Elodie — Education",
                "goal_type": "education",
                "target_amount": 380_000.0,
                "current_from_accounts": ["Elodie — 529 Plan"],
                "current_ratio": 1.0,
                "target_date": "2037-08-15",
                "monthly_contribution": 600.0,
                "expected_return": 0.052,
                "inflation_rate": 0.052,
                "priority": "high",
                "owner_label": "Elodie",
                "description": "In-state university with a private-school buffer.",
            },
            {
                "name": "Home Renovation",
                "goal_type": "life_event",
                "target_amount": 180_000.0,
                "current_from_accounts": ["Everyday Checking"],
                "current_ratio": 0.55,
                "target_date": "2028-06-01",
                "monthly_contribution": 1_800.0,
                "expected_return": 0.038,
                "inflation_rate": 0.04,
                "priority": "low",
                "owner_label": "Camille & Julien",
                "description": "Kitchen and primary bath renovation.",
            },
        ],
    },
]
