"""Household blueprints for the demonstration dataset.

Every figure below is fictional. Account balances are *derived* from the
holdings and cash defined here, so the dataset is internally consistent by
construction rather than by transcription.

`target_value` is the invested market value the generator solves for; the
weights inside `holdings` must sum to 1.0. `gain` is the unrealised gain as a
fraction of cost, which sets the cost basis. A negative gain creates a genuine
loss-harvesting candidate; a large positive gain on a long-held equity lot
creates a gain-harvesting candidate against the section 112A exemption.
"""

from __future__ import annotations

HOUSEHOLDS: list[dict] = [
    {
        # The flagship household. Its headline figures match the product
        # specification exactly: Rs 2.20 Cr assets, Rs 35 L liabilities,
        # Rs 1.85 Cr net worth.
        "key": "sharma",
        "name": "Sharma Family",
        "segment": "private_client",
        "risk_profile": "moderate_growth",
        "city": "Pune",
        "state": "Maharashtra",
        "since": "2016-04-11",
        "benchmark": "BALANCED_60_40",
        "strategy": "Balanced Growth",
        "notes": "Dual-income salaried household. Priorities: retirement corpus, daughters' education and a first home upgrade.",
        "principals": [
            {
                "full_name": "Priya Sharma",
                "birth_date": "1984-06-18",
                "retirement_age": 60,
                "taxpayer_type": "individual",
                "tax_regime": "old",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 42_00_000.0,
                "annual_savings": 9_60_000.0,
                "risk_tolerance": "moderate_growth",
                "is_demo_user": True,
            },
            {
                "full_name": "Rohan Sharma",
                "birth_date": "1982-11-02",
                "retirement_age": 60,
                "taxpayer_type": "individual",
                "tax_regime": "new",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 28_00_000.0,
                "annual_savings": 5_40_000.0,
                "risk_tolerance": "moderate",
            },
        ],
        "members": [
            {"full_name": "Aanya Sharma", "relationship_type": "child", "birth_date": "2012-04-22", "is_dependent": True},
            {"full_name": "Ishaan Sharma", "relationship_type": "child", "birth_date": "2016-09-08", "is_dependent": True},
            {"full_name": "Sushila Sharma", "relationship_type": "parent", "birth_date": "1952-02-14", "is_dependent": True},
        ],
        "accounts": [
            {
                "name": "Zerodha Demat",
                "account_type": "demat",
                "subtype": "individual_demat",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "Zerodha Broking Ltd",
                "target_value": 64_00_000.0,
                "cash": 4_00_000.0,
                "opened_on": "2016-05-02",
                "holdings": [
                    {"symbol": "NIFTYBEES", "weight": 0.220, "gain": 1.42},
                    {"symbol": "RELIANCE", "weight": 0.128, "gain": 0.84},
                    {"symbol": "HDFCBANK", "weight": 0.104, "gain": -0.14},
                    {"symbol": "TCS", "weight": 0.096, "gain": 0.62},
                    {"symbol": "INFY", "weight": 0.074, "gain": -0.09},
                    {"symbol": "ITC", "weight": 0.068, "gain": 0.51},
                    {"symbol": "MON100", "weight": 0.098, "gain": 0.38},
                    {"symbol": "GOLDBEES", "weight": 0.086, "gain": 0.44},
                    {"symbol": "EMBASSY", "weight": 0.062, "gain": -0.11},
                    {"symbol": "BHARATBOND33", "weight": 0.064, "gain": 0.07},
                ],
            },
            {
                "name": "Mutual Fund Folio — CAMS",
                "account_type": "mutual_fund",
                "subtype": "mf_folio",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "CAMS / KFintech Registry",
                "target_value": 40_60_000.0,
                "cash": 1_40_000.0,
                "opened_on": "2016-06-14",
                "holdings": [
                    {"symbol": "PPFAS-FLEXI", "weight": 0.268, "gain": 1.18},
                    {"symbol": "MIRAE-ELSS", "weight": 0.186, "gain": 0.94},
                    {"symbol": "HDFC-MIDCAP", "weight": 0.164, "gain": 1.36},
                    {"symbol": "AXIS-SMALL", "weight": 0.092, "gain": -0.16},
                    {"symbol": "FRANKLIN-USOPP", "weight": 0.078, "gain": 0.22},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.126, "gain": 0.06},
                    {"symbol": "HDFC-SHORT", "weight": 0.086, "gain": 0.04},
                ],
            },
            {
                "name": "NPS Tier I — Priya",
                "account_type": "nps",
                "subtype": "nps_tier_1",
                "tax_treatment": "eet",
                "registration": "individual",
                "custodian": "NSDL / Protean e-Gov",
                "target_value": 13_60_000.0,
                "cash": 40_000.0,
                "opened_on": "2018-03-20",
                "holdings": [
                    {"symbol": "UTINEXT50", "weight": 0.480, "gain": 0.72},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.320, "gain": 0.08},
                    {"symbol": "SBI-GILT", "weight": 0.200, "gain": 0.06},
                ],
            },
            {
                "name": "EPF — Priya & Rohan",
                "account_type": "epf",
                "subtype": "epf_member",
                "tax_treatment": "epf_exempt",
                "registration": "individual",
                "custodian": "EPFO — Regional Office",
                "cash_only": 48_00_000.0,
                "opened_on": "2008-07-01",
            },
            {
                "name": "PPF — Priya",
                "account_type": "ppf",
                "subtype": "ppf",
                "tax_treatment": "eee",
                "registration": "individual",
                "custodian": "HDFC Bank",
                "cash_only": 22_00_000.0,
                "opened_on": "2012-04-05",
            },
            {
                "name": "Sukanya Samriddhi — Aanya",
                "account_type": "sukanya",
                "subtype": "sukanya_samriddhi",
                "tax_treatment": "eee",
                "registration": "guardian",
                "custodian": "HDFC Bank",
                "cash_only": 8_00_000.0,
                "opened_on": "2015-05-30",
            },
            {
                "name": "HDFC Savings Account",
                "account_type": "savings",
                "subtype": "savings",
                "tax_treatment": "taxable",
                "registration": "joint",
                "custodian": "HDFC Bank",
                "cash_only": 12_00_000.0,
                "opened_on": "2012-01-09",
            },
            {
                "name": "Fixed Deposit — HDFC",
                "account_type": "fixed_deposit",
                "subtype": "cumulative_fd",
                "tax_treatment": "taxable",
                "registration": "joint",
                "custodian": "HDFC Bank",
                "cash_only": 6_00_000.0,
                "opened_on": "2023-11-21",
            },
            {
                "name": "Home Loan — HDFC",
                "account_type": "home_loan",
                "subtype": "self_occupied",
                "tax_treatment": "n/a",
                "registration": "joint",
                "custodian": "HDFC Bank",
                "liability": 32_00_000.0,
                "interest_rate": 0.0865,
                "minimum_payment": 42_800.0,
                "opened_on": "2019-06-14",
            },
            {
                "name": "HDFC Regalia Credit Card",
                "account_type": "credit_card",
                "subtype": "revolving",
                "tax_treatment": "n/a",
                "registration": "individual",
                "custodian": "HDFC Bank",
                "liability": 3_00_000.0,
                "interest_rate": 0.42,
                "minimum_payment": 15_000.0,
                "external": True,
                "opened_on": "2017-03-02",
            },
        ],
        "targets": {
            "indian_equity": 0.46,
            "intl_equity": 0.10,
            "debt": 0.28,
            "cash": 0.05,
            "gold": 0.06,
            "alternatives": 0.05,
        },
        "goals": [
            {
                "name": "Retirement at 60",
                "goal_type": "retirement",
                "target_amount": 7_50_00_000.0,
                "current_from_accounts": ["Zerodha Demat", "Mutual Fund Folio — CAMS", "NPS Tier I — Priya", "EPF — Priya & Rohan", "PPF — Priya"],
                "current_ratio": 0.82,
                "target_date": "2044-06-01",
                "monthly_contribution": 1_25_000.0,
                "expected_return": 0.105,
                "inflation_rate": 0.06,
                "priority": "high",
                "owner_label": "Priya & Rohan",
                "description": "Replace 75% of pre-retirement income with EPF, NPS annuity and a personal corpus.",
            },
            {
                "name": "Aanya — Undergraduate Education",
                "goal_type": "education",
                "target_amount": 62_00_000.0,
                "current_from_accounts": ["Sukanya Samriddhi — Aanya"],
                "current_ratio": 1.0,
                "target_date": "2030-07-15",
                "monthly_contribution": 32_000.0,
                "expected_return": 0.085,
                "inflation_rate": 0.09,
                "priority": "high",
                "owner_label": "Aanya",
                "description": "Four years at a private engineering or medical college, or a year abroad.",
            },
            {
                "name": "Ishaan — Undergraduate Education",
                "goal_type": "education",
                "target_amount": 78_00_000.0,
                "current_from_accounts": [],
                "current_amount": 6_40_000.0,
                "target_date": "2034-07-15",
                "monthly_contribution": 26_000.0,
                "expected_return": 0.095,
                "inflation_rate": 0.09,
                "priority": "high",
                "owner_label": "Ishaan",
                "description": "Four years at a private college, allowing for education inflation.",
            },
            {
                "name": "Home Upgrade — Baner",
                "goal_type": "home",
                "target_amount": 1_60_00_000.0,
                "current_from_accounts": ["Fixed Deposit — HDFC", "HDFC Savings Account"],
                "current_ratio": 0.55,
                "target_date": "2031-04-01",
                "monthly_contribution": 55_000.0,
                "expected_return": 0.075,
                "inflation_rate": 0.075,
                "priority": "medium",
                "owner_label": "Priya & Rohan",
                "description": "Larger apartment in Baner, funded partly by selling the current flat.",
            },
            {
                "name": "Parents' Medical Corpus",
                "goal_type": "life_event",
                "target_amount": 40_00_000.0,
                "current_from_accounts": [],
                "current_amount": 11_00_000.0,
                "target_date": "2032-01-01",
                "monthly_contribution": 18_000.0,
                "expected_return": 0.08,
                "inflation_rate": 0.12,
                "priority": "high",
                "owner_label": "Sushila Sharma",
                "description": "Dedicated corpus for elder care, allowing for medical inflation well above headline CPI.",
            },
        ],
    },
    {
        "key": "reddy",
        "name": "Reddy Household",
        "segment": "private_client",
        "risk_profile": "growth",
        "city": "Hyderabad",
        "state": "Telangana",
        "since": "2019-09-04",
        "benchmark": "AGGRESSIVE_80_20",
        "strategy": "Global Growth",
        "notes": "Founder liquidity event in 2023. Focus on diversifying away from a concentrated single-stock position.",
        "principals": [
            {
                "full_name": "Karthik Reddy",
                "birth_date": "1981-03-27",
                "retirement_age": 55,
                "taxpayer_type": "individual",
                "tax_regime": "new",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 1_40_00_000.0,
                "annual_savings": 48_00_000.0,
                "risk_tolerance": "growth",
            },
            {
                "full_name": "Divya Reddy",
                "birth_date": "1983-12-05",
                "retirement_age": 58,
                "taxpayer_type": "individual",
                "tax_regime": "old",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 36_00_000.0,
                "annual_savings": 9_00_000.0,
                "risk_tolerance": "moderate_growth",
            },
        ],
        "members": [
            {"full_name": "Nila Reddy", "relationship_type": "child", "birth_date": "2017-07-19", "is_dependent": True},
        ],
        "accounts": [
            {
                "name": "Reddy Demat — Zerodha",
                "account_type": "demat",
                "subtype": "individual_demat",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "Zerodha Broking Ltd",
                "target_value": 4_16_00_000.0,
                "cash": 34_00_000.0,
                "opened_on": "2019-10-02",
                "holdings": [
                    {"symbol": "RELIANCE", "weight": 0.286, "gain": 3.84},
                    {"symbol": "NIFTYBEES", "weight": 0.164, "gain": 0.92},
                    {"symbol": "TCS", "weight": 0.108, "gain": 0.66},
                    {"symbol": "MON100", "weight": 0.124, "gain": 0.48},
                    {"symbol": "MAFANG", "weight": 0.062, "gain": -0.18},
                    {"symbol": "GOLDBEES", "weight": 0.082, "gain": 0.39},
                    {"symbol": "EMBASSY", "weight": 0.058, "gain": -0.12},
                    {"symbol": "INDIGRID", "weight": 0.048, "gain": 0.14},
                    {"symbol": "BHARATBOND33", "weight": 0.068, "gain": 0.08},
                ],
            },
            {
                "name": "Reddy MF Folio",
                "account_type": "mutual_fund",
                "subtype": "mf_folio",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "CAMS / KFintech Registry",
                "target_value": 1_84_00_000.0,
                "cash": 6_00_000.0,
                "opened_on": "2019-11-20",
                "holdings": [
                    {"symbol": "PPFAS-FLEXI", "weight": 0.312, "gain": 1.06},
                    {"symbol": "HDFC-MIDCAP", "weight": 0.208, "gain": 1.24},
                    {"symbol": "AXIS-SMALL", "weight": 0.116, "gain": -0.14},
                    {"symbol": "FRANKLIN-USOPP", "weight": 0.104, "gain": 0.26},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.152, "gain": 0.07},
                    {"symbol": "SBI-GILT", "weight": 0.108, "gain": 0.05},
                ],
            },
            {
                "name": "NPS Tier I — Karthik",
                "account_type": "nps",
                "subtype": "nps_tier_1",
                "tax_treatment": "eet",
                "registration": "individual",
                "custodian": "NSDL / Protean e-Gov",
                "target_value": 28_00_000.0,
                "cash": 80_000.0,
                "opened_on": "2019-02-20",
                "holdings": [
                    {"symbol": "UTINEXT50", "weight": 0.560, "gain": 0.84},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.260, "gain": 0.09},
                    {"symbol": "SBI-GILT", "weight": 0.180, "gain": 0.07},
                ],
            },
            {
                "name": "EPF — Karthik",
                "account_type": "epf",
                "subtype": "epf_member",
                "tax_treatment": "epf_exempt",
                "registration": "individual",
                "custodian": "EPFO — Regional Office",
                "cash_only": 62_00_000.0,
                "opened_on": "2006-08-01",
            },
            {
                "name": "PPF — Divya",
                "account_type": "ppf",
                "subtype": "ppf",
                "tax_treatment": "eee",
                "registration": "individual",
                "custodian": "Kotak Mahindra Bank",
                "cash_only": 26_00_000.0,
                "opened_on": "2010-04-08",
            },
            {
                "name": "Kotak Savings",
                "account_type": "savings",
                "subtype": "savings",
                "tax_treatment": "taxable",
                "registration": "joint",
                "custodian": "Kotak Mahindra Bank",
                "cash_only": 38_00_000.0,
                "opened_on": "2019-10-02",
            },
            {
                "name": "Home Loan — Kotak",
                "account_type": "home_loan",
                "subtype": "self_occupied",
                "tax_treatment": "n/a",
                "registration": "joint",
                "custodian": "Kotak Mahindra Bank",
                "liability": 1_28_00_000.0,
                "interest_rate": 0.0885,
                "minimum_payment": 1_18_000.0,
                "opened_on": "2021-04-30",
            },
        ],
        "targets": {
            "indian_equity": 0.48,
            "intl_equity": 0.16,
            "debt": 0.20,
            "cash": 0.04,
            "gold": 0.06,
            "alternatives": 0.06,
        },
        "goals": [
            {
                "name": "Financial Independence at 55",
                "goal_type": "retirement",
                "target_amount": 32_00_00_000.0,
                "current_from_accounts": ["Reddy Demat — Zerodha", "Reddy MF Folio", "NPS Tier I — Karthik", "EPF — Karthik"],
                "current_ratio": 0.86,
                "target_date": "2036-03-01",
                "monthly_contribution": 4_20_000.0,
                "expected_return": 0.11,
                "inflation_rate": 0.06,
                "priority": "high",
                "owner_label": "Karthik & Divya",
                "description": "Step back from operating roles at 55 with a corpus that supports a 35-year retirement.",
            },
            {
                "name": "Nila — Overseas Education",
                "goal_type": "education",
                "target_amount": 1_80_00_000.0,
                "current_from_accounts": [],
                "current_amount": 34_00_000.0,
                "target_date": "2035-08-15",
                "monthly_contribution": 65_000.0,
                "expected_return": 0.095,
                "inflation_rate": 0.085,
                "priority": "high",
                "owner_label": "Nila",
                "description": "Undergraduate degree abroad, allowing for currency depreciation and fee inflation.",
            },
            {
                "name": "Family Charitable Trust",
                "goal_type": "legacy",
                "target_amount": 5_00_00_000.0,
                "current_from_accounts": [],
                "current_amount": 62_00_000.0,
                "target_date": "2038-01-01",
                "monthly_contribution": 1_40_000.0,
                "expected_return": 0.09,
                "inflation_rate": 0.06,
                "priority": "medium",
                "owner_label": "Reddy Family Trust",
                "description": "Endow a registered charitable trust focused on education access in Telangana.",
            },
        ],
    },
    {
        "key": "iyer",
        "name": "Iyer Family Office",
        "segment": "family_office",
        "risk_profile": "conservative_growth",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "since": "2011-05-18",
        "benchmark": "CONSERVATIVE_30_70",
        "strategy": "Capital Preservation",
        "notes": "Third-generation business family. HUF alongside individual holdings; distributions support four households.",
        "principals": [
            {
                "full_name": "Lakshmi Iyer",
                "birth_date": "1958-09-30",
                "retirement_age": 62,
                "taxpayer_type": "senior_citizen",
                "tax_regime": "old",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 68_00_000.0,
                "annual_savings": 12_00_000.0,
                "risk_tolerance": "conservative",
            },
        ],
        "members": [
            {"full_name": "Suresh Iyer", "relationship_type": "child", "birth_date": "1984-01-24", "is_dependent": False},
            {"full_name": "Meera Iyer-Nair", "relationship_type": "child", "birth_date": "1987-06-11", "is_dependent": False},
            {"full_name": "Ananya Iyer", "relationship_type": "grandchild", "birth_date": "2014-03-03", "is_dependent": False},
        ],
        "accounts": [
            {
                "name": "Iyer HUF — Demat",
                "account_type": "huf",
                "subtype": "huf_demat",
                "tax_treatment": "taxable",
                "registration": "huf",
                "custodian": "Zerodha Broking Ltd",
                "target_value": 11_20_00_000.0,
                "cash": 96_00_000.0,
                "opened_on": "2011-06-01",
                "holdings": [
                    {"symbol": "NIFTYBEES", "weight": 0.184, "gain": 2.24},
                    {"symbol": "HDFCBANK", "weight": 0.086, "gain": 0.42},
                    {"symbol": "ITC", "weight": 0.074, "gain": 1.66},
                    {"symbol": "TCS", "weight": 0.068, "gain": 1.18},
                    {"symbol": "MON100", "weight": 0.092, "gain": 0.52},
                    {"symbol": "BHARATBOND33", "weight": 0.196, "gain": 0.09},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.128, "gain": 0.08},
                    {"symbol": "SBI-GILT", "weight": 0.084, "gain": 0.06},
                    {"symbol": "GOLDBEES", "weight": 0.058, "gain": 0.48},
                    {"symbol": "EMBASSY", "weight": 0.030, "gain": -0.08},
                ],
            },
            {
                "name": "Iyer Private Trust",
                "account_type": "trust",
                "subtype": "private_family_trust",
                "tax_treatment": "taxable",
                "registration": "trust",
                "custodian": "CAMS / KFintech Registry",
                "target_value": 6_40_00_000.0,
                "cash": 44_00_000.0,
                "opened_on": "2014-10-04",
                "holdings": [
                    {"symbol": "PPFAS-FLEXI", "weight": 0.226, "gain": 1.42},
                    {"symbol": "HDFC-SHORT", "weight": 0.238, "gain": 0.05},
                    {"symbol": "ICICI-CORPBOND", "weight": 0.184, "gain": 0.08},
                    {"symbol": "SETFNIF50", "weight": 0.142, "gain": 0.88},
                    {"symbol": "FRANKLIN-USOPP", "weight": 0.086, "gain": 0.19},
                    {"symbol": "GOLDBEES", "weight": 0.070, "gain": 0.41},
                    {"symbol": "MINDSPACE", "weight": 0.054, "gain": -0.09},
                ],
            },
            {
                "name": "Lakshmi — Senior Citizen FD",
                "account_type": "fixed_deposit",
                "subtype": "scss",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "HDFC Bank",
                "cash_only": 62_00_000.0,
                "opened_on": "2020-04-15",
            },
            {
                "name": "Family Office Operating Account",
                "account_type": "savings",
                "subtype": "current",
                "tax_treatment": "taxable",
                "registration": "trust",
                "custodian": "Kotak Mahindra Bank",
                "cash_only": 84_00_000.0,
                "opened_on": "2011-06-01",
            },
        ],
        "targets": {
            "indian_equity": 0.30,
            "intl_equity": 0.08,
            "debt": 0.42,
            "cash": 0.08,
            "gold": 0.07,
            "alternatives": 0.05,
        },
        "goals": [
            {
                "name": "Preserve the HUF Corpus",
                "goal_type": "legacy",
                "target_amount": 26_00_00_000.0,
                "current_from_accounts": ["Iyer HUF — Demat"],
                "current_ratio": 1.0,
                "target_date": "2035-01-01",
                "monthly_contribution": 0.0,
                "expected_return": 0.085,
                "inflation_rate": 0.06,
                "priority": "high",
                "owner_label": "Iyer HUF",
                "description": "Preserve the real purchasing power of the corpus while funding annual distributions.",
            },
            {
                "name": "Annual Family Distributions",
                "goal_type": "custom",
                "target_amount": 1_20_00_000.0,
                "current_from_accounts": ["Family Office Operating Account"],
                "current_ratio": 1.0,
                "target_date": "2027-12-31",
                "monthly_contribution": 0.0,
                "expected_return": 0.068,
                "inflation_rate": 0.06,
                "priority": "high",
                "owner_label": "Trustee",
                "description": "Fund four beneficiary distributions each year from income rather than corpus.",
            },
        ],
    },
    {
        "key": "menon",
        "name": "Menon Household",
        "segment": "wealth_management",
        "risk_profile": "moderate",
        "city": "Bengaluru",
        "state": "Karnataka",
        "since": "2022-02-08",
        "benchmark": "BALANCED_60_40",
        "strategy": "Balanced",
        "notes": "Young dual-income professionals building toward a first home and an early retirement corpus.",
        "principals": [
            {
                "full_name": "Ananya Menon",
                "birth_date": "1993-08-14",
                "retirement_age": 58,
                "taxpayer_type": "individual",
                "tax_regime": "new",
                "marginal_tax_rate": 0.30,
                "ltcg_tax_rate": 0.125,
                "annual_income": 32_00_000.0,
                "annual_savings": 8_40_000.0,
                "risk_tolerance": "moderate",
            },
        ],
        "members": [
            {"full_name": "Vivek Menon", "relationship_type": "spouse", "birth_date": "1992-05-21", "is_dependent": False},
            {"full_name": "Kiara Menon", "relationship_type": "child", "birth_date": "2021-11-30", "is_dependent": True},
        ],
        "accounts": [
            {
                "name": "Menon Demat",
                "account_type": "demat",
                "subtype": "individual_demat",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "Zerodha Broking Ltd",
                "target_value": 21_40_000.0,
                "cash": 1_60_000.0,
                "opened_on": "2022-03-01",
                "holdings": [
                    {"symbol": "NIFTYBEES", "weight": 0.324, "gain": 0.42},
                    {"symbol": "MON100", "weight": 0.168, "gain": 0.31},
                    {"symbol": "GOLDBEES", "weight": 0.118, "gain": 0.28},
                    {"symbol": "HDFCBANK", "weight": 0.092, "gain": -0.12},
                    {"symbol": "BHARATBOND33", "weight": 0.184, "gain": 0.06},
                    {"symbol": "EMBASSY", "weight": 0.114, "gain": -0.10},
                ],
            },
            {
                "name": "Menon MF Folio",
                "account_type": "mutual_fund",
                "subtype": "mf_folio",
                "tax_treatment": "taxable",
                "registration": "individual",
                "custodian": "CAMS / KFintech Registry",
                "target_value": 16_80_000.0,
                "cash": 60_000.0,
                "opened_on": "2022-04-11",
                "holdings": [
                    {"symbol": "PPFAS-FLEXI", "weight": 0.362, "gain": 0.48},
                    {"symbol": "MIRAE-ELSS", "weight": 0.284, "gain": 0.36},
                    {"symbol": "HDFC-SHORT", "weight": 0.216, "gain": 0.04},
                    {"symbol": "AXIS-SMALL", "weight": 0.138, "gain": -0.13},
                ],
            },
            {
                "name": "EPF — Ananya",
                "account_type": "epf",
                "subtype": "epf_member",
                "tax_treatment": "epf_exempt",
                "registration": "individual",
                "custodian": "EPFO — Regional Office",
                "cash_only": 18_40_000.0,
                "opened_on": "2015-09-04",
            },
            {
                "name": "PPF — Ananya",
                "account_type": "ppf",
                "subtype": "ppf",
                "tax_treatment": "eee",
                "registration": "individual",
                "custodian": "HDFC Bank",
                "cash_only": 9_60_000.0,
                "opened_on": "2017-04-20",
            },
            {
                "name": "HDFC Savings",
                "account_type": "savings",
                "subtype": "savings",
                "tax_treatment": "taxable",
                "registration": "joint",
                "custodian": "HDFC Bank",
                "cash_only": 14_20_000.0,
                "opened_on": "2019-08-08",
            },
            {
                "name": "Home Loan — HDFC",
                "account_type": "home_loan",
                "subtype": "self_occupied",
                "tax_treatment": "n/a",
                "registration": "joint",
                "custodian": "HDFC Bank",
                "liability": 46_00_000.0,
                "interest_rate": 0.0842,
                "minimum_payment": 39_600.0,
                "opened_on": "2022-01-17",
            },
            {
                "name": "Axis Credit Card",
                "account_type": "credit_card",
                "subtype": "revolving",
                "tax_treatment": "n/a",
                "registration": "individual",
                "custodian": "Kotak Mahindra Bank",
                "liability": 1_20_000.0,
                "interest_rate": 0.44,
                "minimum_payment": 6_000.0,
                "external": True,
                "opened_on": "2019-08-08",
            },
        ],
        "targets": {
            "indian_equity": 0.50,
            "intl_equity": 0.12,
            "debt": 0.24,
            "cash": 0.04,
            "gold": 0.06,
            "alternatives": 0.04,
        },
        "goals": [
            {
                "name": "Retirement at 58",
                "goal_type": "retirement",
                "target_amount": 9_60_00_000.0,
                "current_from_accounts": ["Menon Demat", "Menon MF Folio", "EPF — Ananya", "PPF — Ananya"],
                "current_ratio": 0.90,
                "target_date": "2051-08-01",
                "monthly_contribution": 62_000.0,
                "expected_return": 0.105,
                "inflation_rate": 0.06,
                "priority": "high",
                "owner_label": "Ananya & Vivek",
                "description": "A corpus large enough to retire two years before the standard age.",
            },
            {
                "name": "Kiara — Education Fund",
                "goal_type": "education",
                "target_amount": 88_00_000.0,
                "current_from_accounts": [],
                "current_amount": 3_20_000.0,
                "target_date": "2039-07-15",
                "monthly_contribution": 22_000.0,
                "expected_return": 0.10,
                "inflation_rate": 0.09,
                "priority": "high",
                "owner_label": "Kiara",
                "description": "Private undergraduate education in India, with a buffer for a year abroad.",
            },
            {
                "name": "Emergency Corpus",
                "goal_type": "life_event",
                "target_amount": 24_00_000.0,
                "current_from_accounts": ["HDFC Savings"],
                "current_ratio": 1.0,
                "target_date": "2028-06-01",
                "monthly_contribution": 25_000.0,
                "expected_return": 0.065,
                "inflation_rate": 0.06,
                "priority": "medium",
                "owner_label": "Ananya & Vivek",
                "description": "Twelve months of household expenses held in liquid funds and a sweep-in deposit.",
            },
        ],
    },
]
